### ISSUE TITLE
nats-streaming durable subscription

### ISSUE THREAD

**Issue by surryr** [nats-io/nats-streaming-server#572] opened 2018-05-31 13:10 UTC
Hi

We are evaluating nats-streaming to use it for durable subscriptions.
We have prepared simple java consumer with this type of subscriptions and we are killing this consumer without closing the subscription. After restart (withing few seconds) we are observing that few messages was not delivered (e.g. before killing last received message had sequence number 10, after restart it is 15).

Could you please suggest is it related to our configuration?

**Comment by kozlovic** [comment] 2018-05-31 13:45
Thank you for your interest. Could you please answer the following:
- What server and client versions are you using
- Could you show us how you create the durable subscription
- Is the server stopped and restarted too or just the consumer application

On durable restart, the server should redeliver to the durable all unacknowledged message starting at the last that it received before the exit. If there were more messages sent (due to MaxInflight), those messages may be marked as redelivered too. After the attempt to redeliver unacknowledged messages, the server should proceed with the "new" messages.

**Comment by surryr** [comment] 2018-05-31 15:53
Hi Ivan!
Your quick answer is very appreciated.

I'm using gnatsd-v1.1.0 and nats-streaming-server-v0.9.2 (i'm not running embedded nast).
nats-streaming-java is 0.5.0.

This is the way how we are creating subscription.
`private void subscribe() {
        SubscriptionOptions.Builder builder = new SubscriptionOptions.Builder();
        builder.durableName(durableName);

        try {
            subscription.set(streamingConnection.subscribe(subject, this::onMessage, builder.build()));
        } catch (IOException e) {
            LOGGER.warn("Could not set subscription", e);
        } catch (InterruptedException e) {
            LOGGER.warn("Interrupted", e);
            Thread.currentThread().interrupt();
        }
    }`

Only consumer application has been restarted. More over if we shutdown application gracefully (with subscription.close(false);. Close throws NPE, but seems like it has no impact), there is no gap after restart.
After restart we observe, that server tries to redeliver messages, but there is a gap in sequence number. Could you please point out the documentation about MaxInflight?

**Comment by kozlovic** [comment] 2018-06-01 14:57
The MaxInflight would not explain a gap, but more messages being marked as redelivered, even though the application may not have seen them, that's all.
I will try to reproduce with the java client, but was not able with a go client.
If you can easily reproduce this in a test environment, it would be great to run the server with `-SDV` and then reproduce the issue. The tracing should show what's going on.
Thanks!

**Comment by kozlovic** [comment] 2018-06-02 00:06
Looking at the java streaming subscriber example, it does *unsubscribe* on exit if there is no unacknowledged message. We should change that. But this is an example program, your application may not be that.
It is true that the close() can get a NullPointerException and this will need to be fixed. This happens because the returned protocol from the server is empty (since there is no error).

With those little changes, I can't seem to reproduce. If you run your test with server running with -SDV mode, and if you see "Removed durable" from the log it means that your application is calling `unsubscribe()` or `close(true)`, which causes the durable subscription to be removed from the server. Instead, you should see `Suspended` when you simply close the subscription.

**Comment by surryr** [comment] 2018-06-02 05:14
I will reproduce with recommended flags on Monday, whenI'll be in the office.

Thank you.

**Comment by surryr** [comment] 2018-06-04 12:16
Hi Ivan.

We've tried to reproduce it few times, but seems like there were problem on a client side. We could not get into situation when we have a gap with durable subscription any more. Seems to be stable. We also tried to reproduce it with Python client, and didn't observe any problems with it as well. 

Sorry for confusion and thank you for you help.

This issue could be closed.

**Closed** 2018-06-18 17:01 UTC
