### ISSUE TITLE
Clean Close of nats-streaming-server does not trigger immediate disconnect in clients

### ISSUE THREAD

**Issue by coffeefedora** [nats-io/nats-streaming-server#969] opened 2019-11-13 23:26 UTC
I run nats-streaming-server and use the embedded NATS server in my project.   (I'm sending messages over NATS and STAN)  I run this on windows 10, in command line.  If i use ctrl+C to kill the server, clients do not receive disconnect Events.  these events fire after the MaxPingsOut triggers.  

killing the server via Task Manager does send immediate disconnect events to clients.  

While gathering data for replication, I discovered the issue does not happen if NATS 2.1.0 is running, but nats-streaming-server internally is using NATS v2.0.4  so this may be fixed with a simple rebuild of STAN.

Linked Gist shows the steps to reproduce the issue using the Nats Benchmark program (with tweaked code).   

[https://gist.github.com/coffeefedora/a34eb686678e643f0fe093e8dd54274a](https://gist.github.com/coffeefedora/a34eb686678e643f0fe093e8dd54274a)

**Comment by kozlovic** [comment] 2019-11-13 23:48
Your gist link does not work.

I just tested with a Windows 10 VM and it works fine with a Go and C client. I did not try with .NET client. So it could be an issue with the way you test (again, gist not working) or specific to the .NET client. Either way, I don't think this has anything to do with the streaming server.

**Comment by ColinSullivan1** [comment] 2019-11-14 02:27
@coffeefedora, which .NET framework, client, and OS are you using?  Also, are you running the NATS streaming server in docker, or directly via command line?

**Comment by ColinSullivan1** [comment] 2019-11-14 04:11
@coffeefedora @kozlovic , I've been able to reproduce this, and we'll prioritize a fix.  I was planning on getting a .NET release out this week and will hold until this is resolved.

https://github.com/nats-io/nats.net/issues/326

**Comment by coffeefedora** [comment] 2019-11-14 10:28
My first time trying to use the markdown for a link, and apparently i did it wrong :(  

I've updated the gist link.  but it sounds like @ColinSullivan1  was able to reproduce.

**Comment by ColinSullivan1** [comment] 2019-11-14 18:00
@coffeefedora, We've found the issue and I'll be opening a PR soon.  the NATS server was occasionally calling some shutdown code twice, and when this happened the NATS client would immediately encounter a zero length read from the network stream rather than a socket error.  The client wasn't handling this properly and so was getting into an invalid state.

In the meantime, if you `set NATS_DOCKERIZED=1` you shouldn't encounter this issue.

**Comment by kozlovic** [comment] 2019-11-14 20:25
I am closing this issue for now since the underlying error in the .NET library is handled [here](https://github.com/nats-io/nats.net/pull/329).

**Closed by kozlovic** 2019-11-14 20:25 UTC

**Comment by danielwertheim** [comment] 2019-11-14 21:44
@kozlovic @ColinSullivan1  Is there a bug filed to fix this issue in the Server that could be linked here, if not, why is this not seen as an issue? Referring to that the server exists in different manners when being shut down in console.

**Comment by kozlovic** [comment] 2019-11-14 21:46
Having the server shutdown closing its client connections should not be seen as an issue. The server prints "Server exiting.." twice (sometimes) because there is both the signal handler that catches and then exit the process but sometimes the svc code will catch it too and issue a server.Shutdown() (which does close client connections).
In other words, we could very well have the server call Shutdown on signal handler to do a proper shutdown instead of simple os.Exit(). Clients should react the same way to a socket close.

**Comment by danielwertheim** [comment] 2019-11-14 22:16
I agree that the clients should handle this. But I would expect the same behavior from the server when shutting it down and it's in the same state. Not different behavior.

**Comment by kozlovic** [comment] 2019-11-14 22:58
I can maybe update the NATS server.. but, notice that for NATS Streaming server I do call Shutdown () code on exit, which closes/flushes stores but also calls NATS Server Shutdown() code (when embedded). So for embedded cases, this should have always been an issue for .NET clients?

**Comment by kozlovic** [comment] 2019-11-15 02:28
I will update NATS Server to shutdown on ctrl+C, like NATS Streaming does.

**Comment by danielwertheim** [comment] 2019-11-15 06:40
I encountered this using NATS Server. I didn't test the behavior in NATS Streaming.

Sounds good.

**Comment by coffeefedora** [comment] 2019-11-18 19:15
I think @kozlovic change to shutdown NATS on ctrl+c for embedded is the root fix for my initial issue.  I never encountered the bug when running NATS standalone, but always on Stream with embedded.  

the gist link is working now if help reproducing the streaming issue is needed.  Thanks for the quick response!
