### ISSUE TITLE
Monitoring desync on Leader change - Subscription last_sent = 0

### ISSUE THREAD

**Issue by Xswer** [nats-io/nats-streaming-server#1189] opened 2021-05-07 10:16 UTC
Setup:
- nats-streaming-server 0.21.1
- 5 Nodes running in Containers as AWS ECS Tasks
- we have recently expanded Cluster in accordance with - https://github.com/nats-io/nats-streaming-server/issues/1181

When the Cluster Leader is changed the Monitoring endpoints on the Peers show incorrect Subscription state (last_sent = 0). That touches the Channels where we had an Error "leadership lost while committing log". Later the Monitoring will be resyncronized, if a new message is published to the channel. If there are no new incoming messages - no sync happens and last_sent stays at 0. Still the monitoring endpoint of the Leader has a correct state.

### Expected Behaviour
After Leader Change monitoring endpoints of non-leader Nodes reflect the correct Subscription State.

### Actual Behaviour
After Leader Change monitoring endpoints of non-leader Nodes report last_sent = 0 by the Subscriptions, where an Error "leadership lost while committing log" occurred

**Comment by Xswer** [comment] 2021-06-01 12:01
Thank you for the response. We are still investigating what could cause such behaviour, as it became a "default" state for the system. I will provide more information, as soon as we collect any additional input in this direction

**Comment by Xswer** [comment] 2021-06-04 06:23
Issue seems to be resolved after removing the new peers. Right after both peers were removed from the cluster using service message, the monitoring was instantly resynced correctly and has the right state since then. We are now investigating the reasons of the leader changes, that caused desyncs in monitoring. The main assumption is networking problems/limitations in the process of message retranslation between peers. Maybe that could also have an effect on monitoring.

Anyway, I would keep you informed regarding the issue, as we are going to test the behaviour in test env. Thank you for assistance.

**Comment by PBug90** [comment] 2021-08-02 13:38
Xswer and me are part of the same team. We are running a 3-node cluster with nodes A, B and C.

Just today we had another leader-change due to a rolling update and the result was that the monitoring endpoint reported wrong last_sent values for exactly one topic T for two durable subscriptions at all NATS-streaming instances, including the leader itself. 

After the rolling update completed, C was the leader and failed to report the correct last_sent values. I then forced C to exit, resulting in B to become the leader. At this point, A was following B and both did not provide the correct information about the subscriptions of T. 

After C rejoined the cluster after restarting, I force exited B to trigger yet another leader change. C became leader again and correctly provided the information in the monitoring endpoints for topic T. Also A and B (after restarting) provided the correct information at this point.

**Comment by kozlovic** [comment] 2021-08-02 15:08
By "providing the wrong last_sent value", you mean `0` or something else? Also, are those durable subscriptions regular or queue durable subscriptions? Same group or different group?
Any configuration about this topic T and those subscriptions that you could share?

**Comment by PBug90** [comment] 2021-08-03 04:48
last_sent is reported to be equal to 0. I would expect it to be equal to last_seq if no more messages have to be sent to that subscription because we use the difference between last_seq and last_sent as an alerting metric for services that are subscribed to that channel.

If this is intended behaviour, we can change our alerting to respect a last_sent value of 0 and treat it as if it was equal to last_sent if you confirm that a value of 0 means that the subscription is up to date and only updates to the actual sequence number once a new message is received in that channel.

The subscription is configured as durable and as a queue group, even though currently there is only one subscriber active in that queue group.

**Comment by kozlovic** [comment] 2021-08-03 23:49
Would that be possible to provide some configuration details about these channels and getting the output of the endpoint that shows last_sent==0? Would be nice to get it directly from the `http://localhost:8224/streaming/channelsz?subs=1` or `http://<host>:<port>/streaming/channelsz?channel=<channel name>&subs=1` to make sure that the bad info is here and not up higher in the stack if you use prometheus/grafana.

Thanks!

**Comment by PBug90** [comment] 2021-08-09 10:13
All information described above was obtaining from the endpoints anyway.

I replaced all sensitive information with TOPIC and SUBSCRIBER. I also omitted irrelevant subscribers from the array.


**streaming/channelsz?subs=1&channel=TOPIC**
```
{
  "name": "TOPIC",
  "msgs": 1,
  "bytes": 648,
  "first_seq": 171,
  "last_seq": 171,
  "subs_count": 43,
  "subscriptions": [
    {
      "client_id": "SUBSCRIBERd58321f0-f6b0-11eb-88d4-0bf251d16fa5_59bea31f-75c5-4aae-a3f1-d164a156080f",
      "inbox": "_INBOX.DPY1AKWR8098LE1OZ1VDIX",
      "ack_inbox": "_INBOX.qEFWesvgz72KOhGLCCcJsw",
      "queue_name": "SUBSCRIBER-durable-2:SUBSCRIBER-queue-group",
      "is_durable": true,
      "is_offline": false,
      "max_inflight": 1,
      "ack_wait": 30,
      "last_sent": 0,
      "pending_count": 0,
      "is_stalled": false
    }
  ]
}
```

**Comment by kozlovic** [comment] 2021-08-09 16:47
Two things we want to check:
- Are you sure that there is not (or was not) another member in the group? Since MaxInflight is 1 and there is only 1 message in the channel, it could be possible that this queue member above really did not get any message (since it is a queue, the single message in the channel would go to only 1 member of the group).
- You are running the latest server version: since we have a fix in 0.22.1 that *may* be related: https://github.com/nats-io/nats-streaming-server/pull/1203

**Comment by PBug90** [comment] 2021-09-21 07:20
We updated our cluster to 0.22.1 in August but we still observe the behaviour today. 
The following excerpt shows that a subscription still shows last_sent=0 for some subscriptions (in this case arrray element 2)

```
{
   "name":"TOPIC.1",
   "msgs":528,
   "bytes":621498,
   "first_seq":2259,
   "last_seq":2786,
   "subs_count":5,
   "subscriptions":[
      {
         "client_id":"consumercb7d5430-0fad-11ec-a5da-1bfa9ee893d8_e089bba3-4ec5-44c5-b79f-fa8669dfa5c5",
         "inbox":"_INBOX.DSFSJEBTCO5FT9RGS8KAAV",
         "ack_inbox":"_INBOX.Cd403cXoc5GfMpl5ovBBTV",
         "queue_name":"durable:queue-group",
         "is_durable":true,
         "is_offline":true,
         "max_inflight":1,
         "ack_wait":30,
         "last_sent":2512,
         "pending_count":0,
         "is_stalled":false
      },
      {
         "client_id":"consumer3154db80-15ed-11ec-8f69-73e8120424b9_441d03c7-7a81-44d2-84c1-abd821ef4e19",
         "inbox":"_INBOX.V64EU0R0N1IA3CMJZGD8D2",
         "ack_inbox":"_INBOX.2qML3tSQGS6I7x8TXpfaDd",
         "queue_name":"durable-v2:queue-group",
         "is_durable":true,
         "is_offline":false,
         "max_inflight":1,
         "ack_wait":30,
         "last_sent":0,
         "pending_count":0,
         "is_stalled":false
      }
   ]
}
```

**Comment by kozlovic** [comment] 2021-09-21 15:06
@PBug90 Could you provide the full list next time? The above says that there should be 5 subscriptions, but you listed only 2. Having the full list may help explain things.

For instance, the first here, on queue group `durable:queue-group` is currently offline and has received up to `2512` (out of `2786`). There may be other instances of the same group currently running, I don't know.

The second subscription is on a different group: `durable-v2:queue-group`, is online and has indeed not received messages (or at least has last_sent==0). But is there other members of the same group? I don't know. If it is the single instance, what is the start mode? If it is "start new", then if it was started after all current messages in the channel were sent, it is normal.
What you could also do is look at its inbox `_INBOX.V64EU0R0N1IA3CMJZGD8D2` and try to see if you find it in the monitor endpoint `/connz?subs=1` (you would need to do it on server where this app attach to, so may have to go through all to try find it). If you don't find it, try with `/connz?state=closed&subs=1`. If it is closed, then that could explain. But even without be closed, you will get the IP, etc.. that could be useful to see if there is proper network connectivity between the leader and this IP..

**Comment by PBug90** [comment] 2021-09-22 08:43
This is another topic that only has 2 subscriber-services, both currently running at max. 1 concurrent subscriber count. I will provide both the leader output and the output of one follower.
Leader:
````
{
      "name": "ANOTHERTOPIC.1",
      "msgs": 11,
      "bytes": 8065,
      "first_seq": 655,
      "last_seq": 665,
      "subs_count": 2,
      "subscriptions": [
        {
          "client_id": "service2-r4c3f6280-1ae8-11ec-9098-39207ee2c3e8_254edca0-cddb-4e0d-8fe1-101f0ff24a9e",
          "inbox": "_INBOX.X2XAXUTZVOVJUCOK6CGIM0",
          "ack_inbox": "_INBOX.64lZ3RNZ3Gtyoe5cBD5Ch3",
          "queue_name": "service2-durable-2:service2-queue-group",
          "is_durable": true,
          "is_offline": false,
          "max_inflight": 3,
          "ack_wait": 30,
          "last_sent": 665,
          "pending_count": 0,
          "is_stalled": false
        },
        {
          "client_id": "service1-d92eed71-4c81-46f5-acfc-7a7fda4b3f3c_23cd274f-69d0-4fcd-b44f-10a298c910cc",
          "inbox": "_INBOX.X2XAXUTZVOVJUCOK6CXBFC",
          "ack_inbox": "_INBOX.64lZ3RNZ3Gtyoe5cBD5lsg",
          "queue_name": "service1-durable:service1-queue-group",
          "is_durable": true,
          "is_offline": true,
          "max_inflight": 10,
          "ack_wait": 30,
          "last_sent": 665,
          "pending_count": 0,
          "is_stalled": false
        }
      ]
    }
````

Follower:
```
{
      "name": "ANOTHERTOPIC.1",
      "msgs": 11,
      "bytes": 8065,
      "first_seq": 655,
      "last_seq": 665,
      "subs_count": 2,
      "subscriptions": [
        {
          "client_id": "service1-566b2fa0-e3a7-4177-a7ee-3e58040d3a75_1ba81c3a-5c69-4653-bd9e-f881239eca6a",
          "inbox": "_INBOX.X2XAXUTZVOVJUCOK6CWMTU",
          "ack_inbox": "_INBOX.64lZ3RNZ3Gtyoe5cBD5kQa",
          "queue_name": "service1-durable:service1-queue-group",
          "is_durable": true,
          "is_offline": true,
          "max_inflight": 10,
          "ack_wait": 30,
          "last_sent": 665,
          "pending_count": 0,
          "is_stalled": false
        },
        {
          "client_id": "service2-r4c3f6280-1ae8-11ec-9098-39207ee2c3e8_254edca0-cddb-4e0d-8fe1-101f0ff24a9e",
          "inbox": "_INBOX.X2XAXUTZVOVJUCOK6CGIM0",
          "ack_inbox": "_INBOX.64lZ3RNZ3Gtyoe5cBD5Ch3",
          "queue_name": "service2-durable-2:service2-queue-group",
          "is_durable": true,
          "is_offline": false,
          "max_inflight": 3,
          "ack_wait": 30,
          "last_sent": 0,
          "pending_count": 0,
          "is_stalled": false
        }
      ]
    }

```

As you can see, the leader provides the correct last_sent value for service1. 




Initial subscription config for all services is 

````
startWithLastReceived: false
maxInFlight:1
deliverAllAvailable:true
````




As for inbox _INBOX.64lZ3RNZ3Gtyoe5cBD5Ch3, I was able to find it on the /connz?subs=1 output from the leader:

````
    {
      "cid": 5,
      "ip": "127.0.0.1",
      "port": 48522,
      "start": "2021-09-21T04:37:59.631968384Z",
      "last_activity": "2021-09-22T08:41:15.102020569Z",
      "rtt": "96µs",
      "uptime": "1d4h3m49s",
      "idle": "34s",
      "pending_bytes": 0,
      "in_msgs": 0,
      "out_msgs": 0,
      "in_bytes": 0,
      "out_bytes": 0,
      "subscriptions": 17,
      "name": "_NSS-TestCluster-acks",
      "lang": "go",
      "version": "1.11.0",
      "subscriptions_list": [
        "_INBOX.64lZ3RNZ3Gtyoe5cBD4nzP",
        "_INBOX.64lZ3RNZ3Gtyoe5cBD4nv7",
        "_INBOX.64lZ3RNZ3Gtyoe5cBD4ndx",
        "_INBOX.64lZ3RNZ3Gtyoe5cBD5mR0",
        "_INBOX.64lZ3RNZ3Gtyoe5cBD5Cac",
        "_INBOX.64lZ3RNZ3Gtyoe5cBD5Ceu",
        "_INBOX.64lZ3RNZ3Gtyoe5cBD5Ch3",
        "_INBOX.64lZ3RNZ3Gtyoe5cBD5CUB",
        "_INBOX.64lZ3RNZ3Gtyoe5cBD4nog",
        "_INBOX.64lZ3RNZ3Gtyoe5cBD5CYT",
        "_INBOX.64lZ3RNZ3Gtyoe5cBD5CjC",
        "_INBOX.64lZ3RNZ3Gtyoe5cBD4ng6",
        "_INBOX.64lZ3RNZ3Gtyoe5cBD5CS2",
        "_INBOX.64lZ3RNZ3Gtyoe5cBD5Ccl",
        "_INBOX.64lZ3RNZ3Gtyoe5cBD5CWK",
        "_INBOX.64lZ3RNZ3Gtyoe5cBD4niF",
        "_INBOX.64lZ3RNZ3Gtyoe5cBD4nxG"
      ]
    },
````

**Comment by kozlovic** [comment] 2021-09-22 14:55
Looks like you looked for the ack inbox, could instead look for the inbox (_INBOX.X2XAXUTZVOVJUCOK6CGIM0)?

**Comment by PBug90** [comment] 2021-09-22 15:03
````
    {
      "cid": 136,
      "ip": "172.29.123.219",
      "port": 60010,
      "start": "2021-09-21T14:29:15.82682507Z",
      "last_activity": "2021-09-22T14:25:40.6624109Z",
      "stop": "2021-09-22T14:25:40.666495007Z",
      "reason": "Client Closed",
      "rtt": "335µs",
      "uptime": "23h56m24s",
      "idle": "0s",
      "pending_bytes": 0,
      "in_msgs": 20115,
      "out_msgs": 20115,
      "in_bytes": 414519,
      "out_bytes": 2201,
      "subscriptions": 7,
      "lang": "node",
      "version": "1.4.12",
      "subscriptions_list": [
        "_INBOX.X2XAXUTZVOVJUCOK6CGI6O.*",
        "_INBOX.X2XAXUTZVOVJUCOK6CGIEC",
        "_INBOX.X2XAXUTZVOVJUCOK6CGIM0",
        "_INBOX.X2XAXUTZVOVJUCOK6CGITO",
        "_INBOX.X2XAXUTZVOVJUCOK6CGHV6",
        "_INBOX.X2XAXUTZVOVJUCOK6CGHZ0",
        "_STAN.acks.X2XAXUTZVOVJUCOK6CGHRC"
      ]
    }
````

It only appears in the third cluster member in follower mode and i had to filter for closed connections: connz?subs=1&state=closed.

**Comment by kozlovic** [comment] 2021-09-22 16:06
To answer previous question, see the "stop" date for that closed connection and check with servers timestamps to see if the follower started after that, or maybe there were some leader re-election..

**Comment by PBug90** [comment] 2021-09-23 13:28
The last restart of the whole cluster was in the morning of that day with the last leader election happening at 2021-09-21T04:42:58.491Z. No restarts since then. Stop/Start-Configuration makes sure that only one instance of a given cluster member is running at any time, but an automated update process can cause all cluster members to be shut down after one another in a short timeframe.

I checked the logs of all cluster members and filtered for cid:136


Follower (C):
````
[1] 2021/09/21 10:30:20.979739 [DBG] 10.1.2.3:17760 - cid:136 - Client connection created
[1] 2021/09/21 10:30:23.223965 [DBG] 10.1.2.3:17760 - cid:136 - "v1.4.12:node" - Client Ping Timer
[1] 2021/09/21 10:32:23.224350 [DBG] 10.1.2.3:17760 - cid:136 - "v1.4.12:node" - Client Ping Timer
[1] 2021/09/21 10:32:23.224376 [DBG] 10.1.2.3:17760 - cid:136 - "v1.4.12:node" - Delaying PING due to client activity 12s ago
[1] 2021/09/21 10:34:23.225229 [DBG] 10.1.2.3:17760 - cid:136 - "v1.4.12:node" - Client Ping Timer
[1] 2021/09/21 10:34:23.225249 [DBG] 10.1.2.3:17760 - cid:136 - "v1.4.12:node" - Delaying PING due to client activity 12s ago
[1] 2021/09/21 10:35:38.813759 [DBG] 10.1.2.3:17760 - cid:136 - "v1.4.12:node" - Client connection closed: Read Error
````

Note: I changed that IP-Address to 10.1.2.3 in above log output since it does not refer to a cluster member.


Leader (B):
````
[1] 2021/09/21 11:41:32.327963 [DBG] 172.29.123.219:54406 - cid:136 - Client connection created
[1] 2021/09/21 11:41:34.516758 [DBG] 172.29.123.219:54406 - cid:136 - "v1.4.12:node" - Client Ping Timer
[1] 2021/09/21 11:42:12.191418 [DBG] 172.29.123.219:54406 - cid:136 - "v1.4.12:node" - Client connection closed: Client Closed
````


Follower(A)
````
[1] 2021/09/21 14:29:15.826873 [DBG] 172.29.123.219:60010 - cid:136 - Client connection created
--
[1] 2021/09/21 14:29:17.937432 [DBG] 172.29.123.219:60010 - cid:136 - "v1.4.12:node" - Client Ping Timer
[1] 2021/09/21 14:31:17.938422 [DBG] 172.29.123.219:60010 - cid:136 - "v1.4.12:node" - Client Ping Timer
[1] 2021/09/21 14:31:17.938443 [DBG] 172.29.123.219:60010 - cid:136 - "v1.4.12:node" - Delaying PING due to client activity 2s ago
[1] 2021/09/21 14:33:17.939044 [DBG] 172.29.123.219:60010 - cid:136 - "v1.4.12:node" - Client Ping Timer
[1] 2021/09/21 14:33:17.939064 [DBG] 172.29.123.219:60010 - cid:136 - "v1.4.12:node" - Delaying PING due to client activity 2s ago
[1] 2021/09/21 14:35:17.939236 [DBG] 172.29.123.219:60010 - cid:136 - "v1.4.12:node" - Client Ping Timer
[1] 2021/09/21 14:35:17.939256 [DBG] 172.29.123.219:60010 - cid:136 - "v1.4.12:node" - Delaying PING due to client activity 2s ago
...

[1] 2021/09/22 14:23:18.531983 [DBG] 172.29.123.219:60010 - cid:136 - "v1.4.12:node" - Client Ping Timer
--
[1] 2021/09/22 14:23:18.532004 [DBG] 172.29.123.219:60010 - cid:136 - "v1.4.12:node" - Delaying PING due to client activity 4s ago
[1] 2021/09/22 14:25:18.532960 [DBG] 172.29.123.219:60010 - cid:136 - "v1.4.12:node" - Client Ping Timer
[1] 2021/09/22 14:25:18.532981 [DBG] 172.29.123.219:60010 - cid:136 - "v1.4.12:node" - Delaying PING due to client activity 4s ago
[1] 2021/09/22 14:25:40.666337 [DBG] 172.29.123.219:60010 - cid:136 - "v1.4.12:node" - Client connection closed: Client Closed

````

I think this behaviour is odd? Especially because the timestamps of  *Client connection created* are off by a large margin.

**Comment by kozlovic** [comment] 2021-09-23 15:27
The cid is not globally unique. It is per server and for its lifetime. So perfectly possible to have completely different connections with same cid on different servers.

Also, the timestamp in the endpoint as you can see is "zulu/utc" time. The time in server may be local time. 

Like you said, if the inbox is only found in 1 server for that closed connection on server C, then that's the one you would need to check. The point is that this client connection seem to be closed. Is it still showing in the channelsz endpoint? It should not.
But that gives me maybe some clue as to a client that may have received messages but is then closed - but not marked as closed in the leader - and then a follower starts, it may not have the info about last_sent maybe...

**Comment by PBug90** [comment] 2021-09-23 16:33
No follower had restarted since the leader election at 2021-09-21T04:42:58.491Z

The client was restarted 2 minutes after its predecessor disconnected, successfully joining the durable subscription but still the monitoring endpoint did not sync up. 

This is output from Follower(C):

````

[1] 2021/09/22 14:25:40.676759 [DBG] STREAM: [Client:service2-4c3f6280-1ae8-11ec-9098-39207ee2c3e8_254edca0-cddb-4e0d-8fe1-101f0ff24a9e] Suspended durable queue subscription, subject=TOPIC.7, inbox=_INBOX.X2XAXUTZVOVJUCOK6CGIEC, queue=service2-durable:service2-queue-group, subid=20646

[1] 2021/09/22 14:25:40.676842 [DBG] STREAM: [Client:service2-4c3f6280-1ae8-11ec-9098-39207ee2c3e8_254edca0-cddb-4e0d-8fe1-101f0ff24a9e] Suspended durable queue subscription, subject=ANOTHERTOPCIC.1, inbox=_INBOX.X2XAXUTZVOVJUCOK6CGIM0, queue=service2-durable-2:service2-queue-group, subid=188
[1] 2021/09/22 14:25:40.676910 [DBG] STREAM: [Client:service2-4c3f6280-1ae8-11ec-9098-39207ee2c3e8_254edca0-cddb-4e0d-8fe1-101f0ff24a9e] Suspended durable queue subscription, subject=SOMETOPIC.7, inbox=_INBOX.X2XAXUTZVOVJUCOK6CGITO, queue=service2-durable-2:service2-queue-group, subid=276
[1] 2021/09/22 14:25:40.676950 [DBG] STREAM: [Client:service2-4c3f6280-1ae8-11ec-9098-39207ee2c3e8_254edca0-cddb-4e0d-8fe1-101f0ff24a9e] Closed (Inbox=_INBOX.X2XAXUTZVOVJUCOK6CGHV6)
[1] 2021/09/22 14:27:29.172716 [DBG] STREAM: [Client:service2-371076f0-1bb1-11ec-9268-557d7a77cfef_388fcde8-a99c-4f8e-92b5-a6b7f30adab4] Connected (Inbox=_INBOX.7MC199QZP4RQR9NEJEG0KG)
[1] 2021/09/22 14:27:29.184420 [DBG] STREAM: [Client:service2-371076f0-1bb1-11ec-9268-557d7a77cfef_388fcde8-a99c-4f8e-92b5-a6b7f30adab4] Resumed durable queue subscription, subject=TOPIC.7, inbox=_INBOX.7MC199QZP4RQR9NEJEG119, queue=service2-durable:service2-queue-group, subid=20646
[1] 2021/09/22 14:27:29.195113 [DBG] STREAM: [Client:service2-371076f0-1bb1-11ec-9268-557d7a77cfef_388fcde8-a99c-4f8e-92b5-a6b7f30adab4] Resumed durable queue subscription, subject=ANOTHERTOPCIC.1, inbox=_INBOX.7MC199QZP4RQR9NEJEG17Z, queue=service2-durable-2:service2-queue-group, subid=188
[1] 2021/09/22 14:27:29.276101 [DBG] STREAM: [Client:service2-371076f0-1bb1-11ec-9268-557d7a77cfef_388fcde8-a99c-4f8e-92b5-a6b7f30adab4] Resumed durable queue subscription, subject=SOMETOPIC.7, inbox=_INBOX.7MC199QZP4RQR9NEJEG1EP, queue=service2-durable-2:service2-queue-group, subid=276
````

That specific client isnt showing in the monitoring endpoint, but the replacement correctly did show. Still, the correct last_sent value was not updated. It was correctly updated once a message was received and now shows the correct last_sent value.

**Comment by kozlovic** [comment] 2021-09-23 17:09
Ok, will look into this.. Just a question: this subscription did exist before the upgrade to v0.22.1, right? The fix to last_sent in the snapshot exists only in that release, but even if the record existed before, after a new snapshot, that should have updated it.

**Comment by PBug90** [comment] 2021-09-24 07:49
Correct, that subscription existed before the upgrade.

**Comment by kozlovic** [comment] 2021-09-27 15:08
I spent quite some time trying to find where the issue would be and I could not find it. Are you sure all servers have been upgraded? Also, do you see any trace in the log regarding snapshots, which would translate to an `[INF] Deleting raft logs from` trace?
Since the subscription existed before the upgrade and if the snapshot was made prior to the update but there was not one since, it could be the reason.

**Comment by PBug90** [comment] 2021-09-28 07:13
There are plenty of log entries that contain "Deleting raft logs from":

````
[1] 2021/09/22 06:58:08.711563 [INF] STREAM: Deleting raft logs from 146125661 to 146136257
[1] 2021/09/22 07:43:41.557035 [INF] STREAM: Deleting raft logs from 146136258 to 146145166
[1] 2021/09/22 08:40:06.916705 [INF] STREAM: Deleting raft logs from 146145167 to 146153373
[1] 2021/09/22 09:36:17.207909 [INF] STREAM: Deleting raft logs from 146153374 to 146163401
[1] 2021/09/22 10:28:20.391225 [INF] STREAM: Deleting raft logs from 146163402 to 146172046
[1] 2021/09/22 11:00:06.666948 [INF] STREAM: Deleting raft logs from 146172047 to 146180393
[1] 2021/09/22 12:01:27.036323 [INF] STREAM: Deleting raft logs from 146180394 to 146188860
[1] 2021/09/22 13:07:57.106988 [INF] STREAM: Deleting raft logs from 146188861 to 146197120
[1] 2021/09/22 14:22:58.353404 [INF] STREAM: Deleting raft logs from 146197121 to 146205533
[1] 2021/09/22 15:14:16.886220 [INF] STREAM: Deleting raft logs from 146205534 to 146213975
[1] 2021/09/22 16:02:01.978204 [INF] STREAM: Deleting raft logs from 146213976 to 146222564
[1] 2021/09/22 16:40:26.360325 [INF] STREAM: Deleting raft logs from 146222565 to 146230847
````

I also double checked that all cluster members run 0.22.1.

**Comment by PBug90** [comment] 2021-09-28 07:41
Just this morning the issue resurfaced when we redeployed a client application. The server topology did not change though, so no leader election happened and no cluster member was restarted.

We restarted a client application, it successfully reconnected using the same durablename/queuegroup combination and both cluster members that are in follower mode now incorrectly report last_sent=0 for that subscription. The leader correctly reports the last_sent value equal to the last_seq of the topic.

The redeploy killed the client application that was previously running, resulting in "Timed out on heartbeats" logs in the leader log. The "Deleting raft logs from" message occured multiple times after that client restarted, but the follower monitoring endpoints did not sync up.

**Comment by kozlovic** [comment] 2021-09-28 15:36
@PBug90 Ok, so I think we are getting somewhere. Here are the steps I think are happening:

- Create a queue durable with client ID "instance1".
- This subscription receives messages and its last_sent is > 0 an all servers monitoring endpoints
- This subscription is not stopped cleanly
- A member restart with the same queue group/durable but with different client ID
- For a bit, there are 2 members of the same group, one with last_sent > 0, one with last_sent == 0 on all servers (assuming no new message has been sent). This is expected since new member did not receive any message yet.
- The old member times out due to heartbeat and now only one member is present and on the leader its last_sent is updated to the last_sent of the member now gone, but stays at 0 in the followers.
- As soon as a new message is received, the last_sent is properly updated on all servers' monitoring endpoint.

I can see that it would be happening. The reason it is correct in the leader is because this is a runtime update that when the old member with last_sent > 0 is removed, the server detects that the sole member is the new one and likely update its last_sent to reflect the group's last_sent. However, this part is executed only in the leader (or standalone). I will see if that can be improved..

**Comment by kozlovic** [comment] 2021-09-28 20:44
@PBug90 Not sure if you can run servers built from branch/pr, but I have PR #1213 which fixes the issue that I have described above, which I think may be what you have observed. If you could test that would be great.

**Closed** 2021-09-28 22:07 UTC

**Comment by PBug90** [comment] 2021-09-29 08:32
I have built and deployed the current master branch with your fix and will report back if the issue arises again.

**Comment by kozlovic** [comment] 2021-10-04 14:59
@PBug90 I will see if I can have a v0.22.2 release this week.
