### ISSUE TITLE
Subscribe request timeout on 'topic.name' till server restart

### ISSUE THREAD

**Issue by ld100** [nats-io/nats-streaming-server#1211] opened 2021-09-08 15:02 UTC
I'm using Nats Streaming v0.22.1 in a cluster of 3 servers.

Have clients in Ruby, Go and C#, all using latest version of Nats streaming libraries. All 3 using non-durable subscriptions from specified dates. From time to time all 3 are getting timeout error on subscribing different channels. In Ruby client in looks like this:
`STAN::SubReqTimeoutError: stan: subscribe request timeout on 'topic.name'`.
The error persists till you restart Nats Streaming servers.

Server logs does not show anything suspicious:
```
Sep 08 14:21:19 ip-10-1-0-202 nats-streaming-server[64688]: [64688] 2021/09/08 14:21:19.272701 [INF] STREAM: Recovered 20 channel(s)
Sep 08 14:21:19 ip-10-1-0-202 nats-streaming-server[64688]: [64688] 2021/09/08 14:21:19.272761 [INF] STREAM: Cluster Node ID : qa-03
Sep 08 14:21:19 ip-10-1-0-202 nats-streaming-server[64688]: [64688] 2021/09/08 14:21:19.272772 [INF] STREAM: Cluster Log Path: /home/nats/nats/clusterlogs
Sep 08 14:21:19 ip-10-1-0-202 nats-streaming-server[64688]: [64688] 2021/09/08 14:21:19.272776 [INF] STREAM: Cluster known peers:
Sep 08 14:21:19 ip-10-1-0-202 nats-streaming-server[64688]: [64688] 2021/09/08 14:21:19.272783 [INF] STREAM: peer 1: "qa-01"
Sep 08 14:21:19 ip-10-1-0-202 nats-streaming-server[64688]: [64688] 2021/09/08 14:21:19.272788 [INF] STREAM: peer 2: "qa-02"
Sep 08 14:21:19 ip-10-1-0-202 nats-streaming-server[64688]: [64688] 2021/09/08 14:21:19.293688 [INF] STREAM: Message store is RAFT_FILE
Sep 08 14:21:19 ip-10-1-0-202 nats-streaming-server[64688]: [64688] 2021/09/08 14:21:19.293699 [INF] STREAM: Store location: /home/nats/nats
Sep 08 14:21:19 ip-10-1-0-202 nats-streaming-server[64688]: [64688] 2021/09/08 14:21:19.293723 [INF] STREAM: ---------- Store Limits ----------
Sep 08 14:21:19 ip-10-1-0-202 nats-streaming-server[64688]: [64688] 2021/09/08 14:21:19.293727 [INF] STREAM: Channels:                  100 *
Sep 08 14:21:19 ip-10-1-0-202 nats-streaming-server[64688]: [64688] 2021/09/08 14:21:19.293731 [INF] STREAM: --------- Channels Limits --------
Sep 08 14:21:19 ip-10-1-0-202 nats-streaming-server[64688]: [64688] 2021/09/08 14:21:19.293735 [INF] STREAM:   Subscriptions:          1000 *
Sep 08 14:21:19 ip-10-1-0-202 nats-streaming-server[64688]: [64688] 2021/09/08 14:21:19.293738 [INF] STREAM:   Messages     :       1000000 *
Sep 08 14:21:19 ip-10-1-0-202 nats-streaming-server[64688]: [64688] 2021/09/08 14:21:19.293742 [INF] STREAM:   Bytes        :     976.56 MB *
Sep 08 14:21:19 ip-10-1-0-202 nats-streaming-server[64688]: [64688] 2021/09/08 14:21:19.293746 [INF] STREAM:   Age          :     unlimited *
Sep 08 14:21:19 ip-10-1-0-202 nats-streaming-server[64688]: [64688] 2021/09/08 14:21:19.293750 [INF] STREAM:   Inactivity   :     unlimited *
Sep 08 14:21:19 ip-10-1-0-202 nats-streaming-server[64688]: [64688] 2021/09/08 14:21:19.293753 [INF] STREAM: ----------------------------------
Sep 08 14:21:20 ip-10-1-0-202 nats-streaming-server[64688]: [64688] 2021/09/08 14:21:20.152509 [INF] 10.1.0.40:6222 - rid:10 - Route connection created
Sep 08 14:21:20 ip-10-1-0-202 nats-streaming-server[64688]: [64688] 2021/09/08 14:21:20.166010 [INF] 10.1.0.124:43698 - rid:11 - Route connection created
```

Previously used older Nats Streaming version (0.14.2) and had issues like this maybe twice a year, while on the latest one having the issue every couple days.

**Comment by kozlovic** [comment] 2021-09-08 15:15
You should enable monitoring on those servers (https://docs.nats.io/nats-streaming-concepts/monitoring), then when you can reproduce, I would like you to check with the [`http://<host>:<port>/streaming/channelsz`](https://docs.nats.io/nats-streaming-concepts/monitoring/endpoints#channelsz) endpoint, if you can see this channel. You can list the subscriptions currently attached to it with adding `?subs=1` (see details).

Can you do anything else on that server when that happens? That is, are you able to publish or subscribe to other channels? It may be worth trying to see if the server is somehow deadlocked.  To do so, there is an undocumented endpoint that will gather the stack traces: `http://<host>:<port>/stacksz`.

**Comment by ld100** [comment] 2021-09-09 08:07
Thanks, will check this next time the issue happens.

> Can you do anything else on that server when that happens? That is, are you able to publish or subscribe to other channels?

Yes, the thing is happening only to a single client at a time. Meanwhile other clients work with no issues.

**Comment by kozlovic** [comment] 2021-09-09 21:51
> Yes, the thing is happening only to a single client at a time. Meanwhile other clients work with no issues.

Humm.. this is strange. Are you sure there is no connectivity issues between the client and the server at that time? Make sure that you register error handlers on the connection to report any possible issue there.

Keep us posted.

**Comment by ld100** [comment] 2021-09-14 11:58
Hey @kozlovic, I've caught the issue again, this time with the debug info you've asked for:

https://gist.github.com/ld100/dd296f0536fd8142b0447cd51203681f - this gist contains stack traces from all 3 NATS Streaming servers I use in the cluster.

Also it contains "subs.json" with channel and client that was not able to subscribe. It looks surprising, since scubscription look totally fine there.

Hope stack traces could give any clarity.

**Comment by kozlovic** [comment] 2021-09-14 15:11
The stack is fine, no sign of deadlock or anything. The subs.json not only shows that the subscription was created, but that the server sent the 3 messages there AND they were acknowledged.

Which Go client version are you using? 
Could you post a bit of code on how the subscription is created?
Could it be that either you are for some reason reporting an error from something else than the creation of the subscription?
If all apps (different libs) report the same timeout at the same time, are those apps running on the same machine? Could it be some time sync issue where the machine suddenly moves forward enough to think that there was a timeout, while in reality there is not?

(the reason I ask for Go client version is because since v0.8.3, if a subscription gets a timeout during creation, it sends an unsub to clean up the subscription (in case it is handled by the server after the client has reported the timeout). So if this subscription was created by a Go client *and* there was really a timeout, it should have deleted it and you should not be able to see it in the monitor endpoint. This requires server v0.21.0+ for that to happen because the lib will send an unsub based on the inbox, instead of the normal ackinbox that is returned by the server. So only newer server will lookup the subscription based on inbox if not found from ackinbox lookup). See https://github.com/nats-io/stan.go/pull/347 for details.

**Comment by kozlovic** [comment] 2022-08-09 16:38
Closing this now since there is no update from your side.

**Closed by kozlovic** 2022-08-09 16:38 UTC
