### ISSUE TITLE
Got this after running "go build"

### ISSUE THREAD

**Issue by unisqu** [nats-io/nats-streaming-server#583] opened 2018-06-22 18:33 UTC
# _/src/nats-streaming-server
./nats-streaming-server.go:153:38: cannot use nOpts (type *"github.com/nats-io/gnatsd/server".Options) as type *"github.com/nats-io/nats-streaming-server/vendor/github.com/nats-io/gnatsd/server".Options in argument to "github.com/nats-io/nats-streaming-server/server".RunServerWithOpts
./nats-streaming-server.go:174:2: cannot use natsOpts (type *"github.com/nats-io/nats-streaming-server/vendor/github.com/nats-io/gnatsd/server".Options) as type *"github.com/nats-io/gnatsd/server".Options in return argument

**Comment by kozlovic** [comment] 2018-06-22 18:35
@unisqu Are you embedding NATS Streaming Server in your code? If so, please look at [this](https://github.com/nats-io/nats-streaming-server#embedding-nats-streaming) and see if that helps.

**Comment by unisqu** [comment] 2018-06-23 01:27
can it be run independently?

**Comment by unisqu** [comment] 2018-06-23 07:19
I'm trying to install nats-streaming-server

**Comment by ripienaar** [comment] 2018-06-23 07:21
You can download a release from the releases page. Not sure why your build fails but that’s the more typical route to take

**Comment by unisqu** [comment] 2018-06-23 07:22
gnatsd is working though. I'm running inside docker container. does nats streaming server have one with docker with ubuntu 16.04?

**Comment by kozlovic** [comment] 2018-06-25 15:37
@unisqu As @ripienaar mentioned, you have both the ability to download the executable from the Release pages [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.10.0) or the docker image from [here](https://hub.docker.com/_/nats-streaming/).

Still, I would like to know how did you try to build and how you got this error. I can't reproduce that.
If you don't mind giving some info, like the current path you are in when building and result of `echo $GOPATH`. Thanks!

**Comment by kozlovic** [comment] 2018-06-28 16:22
@unisqu Closing for now. Please re-open if you have more information. Thanks!

**Closed by kozlovic** 2018-06-28 16:22 UTC
