### ISSUE TITLE
"sub close request missing subject" on snapshot replay

### ISSUE THREAD

**Issue by wilstoff** [nats-io/nats-streaming-server#1229] opened 2022-01-12 23:09 UTC
Noticed an interesting issue when running tests while we restarted a node in our cluster.  I don't think this is urgent but seems like snapshot replay can sometimes lead to errors that actually aren't something to worry about, and would prefer if the replay didn't label them as errors in a replay situation.

nats server version: 2.5.0
stan server version: 0.22.1
stan .net client version: 0.2.1 sha a979f0851fc6db6a73c411fc6185ecb90ae4f613
built locally with protobuf version: 3.12.0

Steps 3 node cluster
Create 5 min max age/max inactivity topic
1) subscribe
2) unsubscribe
3) wait 5 min
4) topic disappears from cluster
5) shut down 1 node nats streaming and regular nats
6) wait 1 min
7) start node back up
Replaying of unsubscribe in step 2 occurs and errors out with no subject (because it doesn't exist anymore)

> [22390] 2022/01/12 12:47:49.175600 [INF] STREAM: Channel "riv_stan.stan_test.9b6051b2623a" has been created
> 
> 2022-01-12 18:47:50.103 UTC; Application=ReplicatorManager; Severity=Information; Component=BT.Messaging.Stan; Function=StanConnection.Subscribe; Title="STAN: Subscribing to riv_stan.stan_test.9b6051b2623a"; Reason=""; DurableName=RIV_EQX; LeaveOpenOnShutdown=True; MaxMessagesInFlight=StanDefault; ManualAcks=True; WaitForAckTimeout=StanDefault; StartType=AtBeginning; SequenceStart=0; TimeStart="0001-01-01 00:00:00Z"; TimeAgo=00:00:00; QueueGroup=ReplicatorManager.RIV_EQX; Topic=riv_stan.stan_test.9b6051b2623a; ClientId=replicator1_shard0_RIV_EQX; ClusterId=riv_stan; AllClusterIds=riv_stan; InstanceName=replicator1
> 
> 2022-01-12 18:52:53.530 UTC; Application=ReplicatorManager; Severity=Information; Component=BT.Messaging.Stan; Function=StanConnection.Subscribe; Title="STAN: Subscription Cleanup"; Reason=""; DurableName=RIV_EQX; LeaveOpenOnShutdown=True; MaxMessagesInFlight=StanDefault; ManualAcks=True; WaitForAckTimeout=StanDefault; StartType=AtBeginning; SequenceStart=0; TimeStart="0001-01-01 00:00:00Z"; TimeAgo=00:00:00; QueueGroup=ReplicatorManager.RIV_EQX; Topic=riv_stan.stan_test.9b6051b2623a; ClientId=replicator1_shard0_RIV_EQX; ClusterId=riv_stan; AllClusterIds=riv_stan; InstanceName=replicator1;
> 
> [22390] 2022/01/12 12:57:53.923562 [INF] STREAM: Channel "riv_stan.stan_test.9b6051b2623a" has been deleted
> [22371] 2022/01/12 12:59:40.131088 [INF] Initiating Shutdown...
> [22371] 2022/01/12 12:59:40.132612 [INF] ip:port - gid:15 - Gateway connection closed: Server Shutdown
> [22371] 2022/01/12 12:59:40.192350 [INF] ip:port - rid:29312 - Router connection closed: Server Shutdown
> [22371] 2022/01/12 12:59:40.381266 [INF] ip:port - rid:4 - Router connection closed: Server Shutdown
> [22371] 2022/01/12 12:59:40.809496 [INF] ip:port - gid:14 - Gateway connection closed: Server Shutdown
> [22371] 2022/01/12 12:59:40.815792 [INF] ip:port - gid:16559 - Gateway connection closed: Server Shutdown
> [22390] 2022/01/12 12:59:41.382536 [INF] STREAM: Shutting down.
> [6947] 2022/01/12 13:00:42.450721 [INF] Starting nats-server
> [6947] 2022/01/12 13:00:42.452665 [INF] Starting http monitor on ip:port
> [6976] 2022/01/12 13:00:43.013452 [INF] STREAM: Starting nats-streaming-server[riv_stan] version 0.22.1
> [6976] 2022/01/12 13:00:43.022815 [INF] STREAM: Recovering the state...
> [6976] 2022/01/12 13:02:51.196588 [INF] STREAM: Recovered 10549 channel(s)
> [6976] 2022/01/12 13:02:51.306266 [INF] STREAM: restoring from snapshot
> [6976] 2022/01/12 13:02:53.162096 [ERR] STREAM: [Client:replicator1_shard0_RIV_EQX] sub close request missing subject riv_stan.stan_test.9b6051b2623a

**Comment by kozlovic** [comment] 2022-01-12 23:28
Thanks for the report, I will have a look.

**Comment by guojianyu** [comment] 2022-01-13 11:13
I have a similar problem.

[1] 2022/01/11 11:28:34.021872 [INF] STREAM: Starting nats-streaming-server[test-cluster] version 0.22.0
[1] 2022/01/11 11:28:34.021923 [INF] STREAM: ServerID: G25Eq3oCW6ym7sz1RX2Xk0
[1] 2022/01/11 11:28:34.021945 [INF] STREAM: Go version: go1.16.4
[1] 2022/01/11 11:28:34.021948 [INF] STREAM: Git commit: [528588f]
[1] 2022/01/11 11:28:34.073735 [INF] STREAM: Starting in standby mode
[1] 2022/01/11 11:28:35.393534 [INF] STREAM: Server is active
[1] 2022/01/11 11:28:36.411737 [INF] STREAM: Recovering the state...
[1] 2022/01/11 11:28:36.422315 [INF] STREAM: No recovered state
[1] 2022/01/11 11:28:36.439290 [INF] STREAM: Message store is FILE
[1] 2022/01/11 11:28:36.439319 [INF] STREAM: Store location: /data/stan/store
[1] 2022/01/11 11:28:36.439391 [INF] STREAM: ---------- Store Limits ----------
[1] 2022/01/11 11:28:36.439400 [INF] STREAM: Channels:            unlimited
[1] 2022/01/11 11:28:36.439403 [INF] STREAM: --------- Channels Limits --------
[1] 2022/01/11 11:28:36.439406 [INF] STREAM:   Subscriptions:     unlimited
[1] 2022/01/11 11:28:36.439408 [INF] STREAM:   Messages     :     unlimited
[1] 2022/01/11 11:28:36.439414 [INF] STREAM:   Bytes        :     256.00 GB
[1] 2022/01/11 11:28:36.439416 [INF] STREAM:   Age          :      168h0m0s
[1] 2022/01/11 11:28:36.439420 [INF] STREAM:   Inactivity   :     unlimited *
[1] 2022/01/11 11:28:36.439423 [INF] STREAM: -------- List of Channels --------
[1] 2022/01/11 11:28:36.439425 [INF] STREAM: cloud.>
[1] 2022/01/11 11:28:36.439428 [INF] STREAM: ----------------------------------
[1] 2022/01/11 11:28:36.439431 [INF] STREAM: Streaming Server is ready
[1] 2022/01/12 01:41:33.682532 [INF] STREAM: Channel "cloud.security.2723214a-a9a8-45e0-8a13-bb89e07d8e58" has been created
[1] 2022/01/12 01:43:48.804370 [INF] STREAM: Channel "cloud.security.504ccfa6-e7d4-42d9-9b3c-015be0832228" has been created
[1] 2022/01/12 01:55:49.857582 [INF] STREAM: connection "_NSS-test-cluster-pc" reconnected to NATS Server at "tls://10.96.92.20:4222"
[1] 2022/01/12 01:55:49.859016 [INF] STREAM: connection "_NSS-test-cluster-ft" reconnected to NATS Server at "tls://10.96.96.11:4222"
[1] 2022/01/12 01:55:49.859042 [INF] STREAM: connection "_NSS-test-cluster-acks" reconnected to NATS Server at "tls://10.96.96.11:4222"
[1] 2022/01/12 01:55:49.859470 [INF] STREAM: connection "_NSS-test-cluster-general" reconnected to NATS Server at "tls://10.96.92.20:4222"
[1] 2022/01/12 01:55:49.860237 [INF] STREAM: connection "_NSS-test-cluster-send" reconnected to NATS Server at "tls://10.96.96.11:4222"
[1] 2022/01/12 01:55:49.861336 [INF] STREAM: connection "_NSS-test-cluster-hb" reconnected to NATS Server at "tls://10.96.96.11:4222"
[1] 2022/01/12 01:55:58.759195 [INF] STREAM: connection "_NSS-test-cluster-acks" reconnected to NATS Server at "tls://10.96.92.20:4222"
[1] 2022/01/12 01:55:58.761562 [INF] STREAM: connection "_NSS-test-cluster-send" reconnected to NATS Server at "tls://10.96.92.20:4222"
[1] 2022/01/12 01:55:58.762455 [INF] STREAM: connection "_NSS-test-cluster-hb" reconnected to NATS Server at "tls://10.96.92.20:4222"
[1] 2022/01/12 01:55:58.764333 [INF] STREAM: connection "_NSS-test-cluster-ft" reconnected to NATS Server at "tls://10.96.92.20:4222"
[1] 2022/01/12 01:56:04.429381 [ERR] STREAM: Unable to send FT heartbeat: nats: outbound buffer limit exceeded
[1] 2022/01/12 01:56:06.791222 [ERR] STREAM: Unable to send FT heartbeat: nats: outbound buffer limit exceeded
[1] 2022/01/12 01:56:09.511385 [INF] STREAM: connection "_NSS-test-cluster-hb" reconnected to NATS Server at "nats://nats.nats.svc:4222"
[1] 2022/01/12 01:56:09.781025 [INF] STREAM: connection "_NSS-test-cluster-pc" reconnected to NATS Server at "nats://nats.nats.svc:4222"
[1] 2022/01/12 01:56:09.865042 [ERR] STREAM: Unable to send FT heartbeat: nats: outbound buffer limit exceeded
[1] 2022/01/12 01:56:10.149324 [INF] STREAM: connection "_NSS-test-cluster-send" reconnected to NATS Server at "nats://nats.nats.svc:4222"
[1] 2022/01/12 01:56:10.196308 [INF] STREAM: connection "_NSS-test-cluster-ft" reconnected to NATS Server at "nats://nats.nats.svc:4222"
[1] 2022/01/12 01:56:10.588337 [INF] STREAM: connection "_NSS-test-cluster-acks" reconnected to NATS Server at "nats://nats.nats.svc:4222"
[1] 2022/01/12 01:56:10.753747 [INF] STREAM: connection "_NSS-test-cluster-general" reconnected to NATS Server at "nats://nats.nats.svc:4222"
[1] 2022/01/12 01:58:20.083989 [INF] STREAM: connection "_NSS-test-cluster-hb" reconnected to NATS Server at "tls://10.96.96.70:4222"
[1] 2022/01/12 01:58:20.091473 [INF] STREAM: connection "_NSS-test-cluster-send" reconnected to NATS Server at "tls://10.96.92.42:4222"
[1] 2022/01/12 01:58:20.091538 [INF] STREAM: connection "_NSS-test-cluster-ft" reconnected to NATS Server at "tls://10.96.96.70:4222"
[1] 2022/01/12 01:58:20.091661 [INF] STREAM: connection "_NSS-test-cluster-acks" reconnected to NATS Server at "tls://10.96.96.70:4222"
[1] 2022/01/12 01:58:20.092347 [INF] STREAM: connection "_NSS-test-cluster-pc" reconnected to NATS Server at "tls://10.96.96.70:4222"
[1] 2022/01/12 01:58:20.096483 [INF] STREAM: connection "_NSS-test-cluster-general" reconnected to NATS Server at "tls://10.96.96.70:4222"
[1] 2022/01/12 01:58:24.467231 [INF] STREAM: connection "_NSS-test-cluster-send" reconnected to NATS Server at "tls://10.96.96.70:4222"
[1] 2022/01/12 01:58:29.861231 [ERR] STREAM: Unable to send FT heartbeat: nats: outbound buffer limit exceeded
[1] 2022/01/12 01:58:38.413794 [ERR] STREAM: Unable to send FT heartbeat: nats: outbound buffer limit exceeded
[1] 2022/01/12 01:58:42.274314 [INF] STREAM: connection "_NSS-test-cluster-hb" reconnected to NATS Server at "nats://nats.nats.svc:4222"
[1] 2022/01/12 01:58:42.426749 [INF] STREAM: connection "_NSS-test-cluster-acks" reconnected to NATS Server at "nats://nats.nats.svc:4222"
[1] 2022/01/12 01:58:42.834957 [INF] STREAM: connection "_NSS-test-cluster-general" reconnected to NATS Server at "nats://nats.nats.svc:4222"
[1] 2022/01/12 01:58:43.019619 [INF] STREAM: connection "_NSS-test-cluster-ft" reconnected to NATS Server at "nats://nats.nats.svc:4222"
[1] 2022/01/12 01:58:44.182486 [INF] STREAM: connection "_NSS-test-cluster-pc" reconnected to NATS Server at "nats://nats.nats.svc:4222"
[1] 2022/01/12 01:58:44.352355 [INF] STREAM: connection "_NSS-test-cluster-send" reconnected to NATS Server at "nats://nats.nats.svc:4222"
[1] 2022/01/13 01:57:05.098773 [INF] STREAM: Channel "cloud.system.camera-message" has been created
[1] 2022/01/13 01:59:27.234542 [INF] STREAM: Channel "cloud.system.cameraaunk-files" has been created
[1] 2022/01/13 02:41:09.225792 [INF] STREAM: Channel "cloud.system.camera76xz-files" has been created
[1] 2022/01/13 03:23:38.513641 [INF] STREAM: Channel "cloud.system.cameraoenj-files" has been created
[1] 2022/01/13 04:45:10.374821 [ERR] STREAM: [Client:security-id-backend-1012112818] Timed out on heartbeats
[1] 2022/01/13 05:59:07.339884 [ERR] STREAM: [Client:security-id-backend-1012112818] Timed out on heartbeats
[1] 2022/01/13 08:21:57.293775 [INF] STREAM: Channel "cloud.system.camerazovp-files" has been created
[1] 2022/01/13 09:18:46.024233 [INF] STREAM: Channel "cloud.system.camerakgio-files" has been created
[1] 2022/01/13 09:38:01.446244 [ERR] STREAM: [Client:system-cloud-camera] sub close request for missing client
[1] 2022/01/13 09:38:02.138094 [ERR] STREAM: [Client:system-cloud-camera] sub close request for missing client
[1] 2022/01/13 09:38:18.961439 [ERR] STREAM: [Client:system-cloud-camera] sub close request for missing client
[1] 2022/01/13 09:38:43.963809 [ERR] STREAM: [Client:system-cloud-camera] sub close request for missing client
[1] 2022/01/13 09:39:24.893981 [ERR] STREAM: [Client:system-cloud-camera] sub close request for missing client
[1] 2022/01/13 09:40:45.885272 [ERR] STREAM: [Client:system-cloud-camera] sub close request for missing client
[1] 2022/01/13 09:43:35.903319 [ERR] STREAM: [Client:system-cloud-camera] sub close request for missing client
[1] 2022/01/13 09:48:42.915781 [ERR] STREAM: [Client:system-cloud-camera] sub close request for missing client
[1] 2022/01/13 09:53:45.893044 [ERR] STREAM: [Client:system-cloud-camera] sub close request for missing client
[1] 2022/01/13 09:58:54.911081 [ERR] STREAM: [Client:system-cloud-camera] sub close request for missing client
[1] 2022/01/13 10:03:56.951713 [ERR] STREAM: [Client:system-cloud-camera] sub close request for missing client

**Comment by kozlovic** [comment] 2022-01-13 22:22
@guojianyu That's different. The original poster is about "missing for subject" and that is because, as he explained, the channel has disappeared due to max inactivity, but on replay of the RAFT log, the "sub close" protocol cannot find the channel.
In your case you are using FT, not clustering, and the error is about "missing client", which means that the server has not recovered or already timed-out a client (client ID) but that client is still "connected" and is sending subscription close requests.

**Comment by guojianyu** [comment] 2022-01-14 02:19
> @guojianyu That's different. The original poster is about "missing for subject" and that is because, as he explained, the channel has disappeared due to max inactivity, but on replay of the RAFT log, the "sub close" protocol cannot find the channel. In your case you are using FT, not clustering, and the error is about "missing client", which means that the server has not recovered or already timed-out a client (client ID) but that client is still "connected" and is sending subscription close requests.

@kozlovic Thanks for your response.
this is my streaming server configurations.

stan.conf: |
    http: 8222

    streaming {
      id: test-cluster
      store: file
      dir: /data/stan/store
      ft_group_name: "cloud-cluster"
      file_options {
          buffer_size: 32mb
          slice_max_bytes: 512mb
          parallel_recovery: 64
      }
      nats_server_url: "nats://nats.nats.svc:4222"
      partitioning: true
      replace_durable: true
      store_limits {
          channels: {
           cloud.>: {}
          }
          max_channels: 0
          max_msgs: 0
          max_bytes: 256gb
          max_age: 168h
          max_subs: 0
      }
      tls: {
      verify:   true
      client_cert: "/etc/nats-client-tls-certs/tls.crt"
      client_key: "/etc/nats-client-tls-certs/tls.key"
      client_ca: "/etc/nats-client-tls-certs/ca.crt"
     
     }  
    }

If report this error, the wrong clientID will never work.Restarting the client does not solve the problem.Only restarting the streaming service can solve this problem.
I think enable streaming services  ** replace_durable:true** configurations.restarting the client coding can reconnect the streaming server but no recovery.
Please,How can I fix this problem?

**Comment by kozlovic** [comment] 2022-01-14 03:10
@guojianyu I am sorry, I am not sure I understand everything you said:

> If report this error, the wrong clientID will never work

What do you mean by "wrong clientID"?

Several things that I want to point out to see if it helps with the discussion:
- A client ID, channel name and durable name form a name that the server uses to identify a durable.
- A single instance of a given client ID can connect to the server. If a second client tries to use the same client ID and the server detects that the first instance is still reachable, then the new client is rejected.
- The client library (at least Go, or C that I know of) would report the connection lost if - in the case above - the first client was somehow "not reachable" by the server while the second instance was accepted. When the first client is then able to communicate with the server, it will detect that it is no longer the valid client and close the STAN connection and report it as a connection lost (if you have setup the handler).

The `replace_durable` option is really in the case where a given client tries to start/resume a durable subscription, but either timed-out and thought that the subscription was not created and tries again. Without this option, and if the server had accepted the first start of the durable, it would reject the following attempts as duplicate durable subscriptions. The client would have to close the connection (since the client may not have the subscription object to close since the sc.Subscribe() would have returned an error - say a timeout).

The fact that you get the error "request for missing client" means that the server is processing for a given clientID, a subscription request for a durable that it has detected as being already present, and tries to close it, but then does not find that client, which it should since it is receiving the request from that very same client ID.

So it would be nice to have a reproducible test case, a sequence of events to reproduce this problem.

**Comment by guojianyu** [comment] 2022-01-14 06:21
Thanks for your response.
The "wrong clientID"  mean is  client created with this clientID is not running.
I checked my code and found that the stan connection was not closed after the subscription failed,I don't know if it's relevant.
I tried to reproduce this test case and verify it.

**Comment by guojianyu** [comment] 2022-01-14 06:22
@kozlovic 
Thanks for your response.
The "wrong clientID" mean is client created with this clientID is not running.
I checked my code and found that the stan connection was not closed after the subscription failed,I don't know if it's relevant.
I tried to reproduce this test case and verify it.

**Comment by kozlovic** [comment] 2022-01-14 18:23
@guojianyu I still don't understand. Since it is really different than the original post for this issue, could you please open a new issue and clearly specify the steps to reproduce? Something like:
- Start the server(s) with similar configuration that is attached
- Start a subscription with client ID <value that you use> and channel <channel that you use> and durable name <name that you use>
- ..

Be as accurate as possible in the steps description since what seem to be an irrelevant detail may not be. Once I have a better understanding on what is happening, then I will be able to help you.
Thanks!

**Comment by guojianyu** [comment] 2022-01-17 05:50
> @guojianyu I still don't understand. Since it is really different than the original post for this issue, could you please open a new issue and clearly specify the steps to reproduce? Something like:
> 
> * Start the server(s) with similar configuration that is attached
> * Start a subscription with client ID  and channel  and durable name
> * ..
> 
> Be as accurate as possible in the steps description since what seem to be an irrelevant detail may not be. Once I have a better understanding on what is happening, then I will be able to help you. Thanks!

Thank you so much.
The problem is very difficult to reproduce,this did not appear in recent tests.
The  stan version I use is （github.com/nats-io/stan.go v0.10.0)，I find this version recently fixed a bug.
I'm trying to reproduce the problem then verify the guess and open a new issue.
Best regards.

**Closed** 2022-01-19 00:26 UTC

**Comment by wilstoff** [comment] 2022-01-19 04:21
Thank you for getting to this so fast.  I appreciate the effort.
