### ISSUE TITLE
Manual Ack

### ISSUE THREAD

**Issue by steventanwc** [nats-io/nats-streaming-server#146] opened 2016-08-29 08:15 UTC
When I set  
manualAcks: true 
without durableName
maxInFlight: 1
the messages will be downloaded 1 by 1 only after the I issue msg.ack();

However if I set 
manualAcks: true 
durableName: 'somename'
maxInFlight: 1, 

The manualAcks does not seem to work.

Is manualAcks only works when there is no durableName??

Thanks in advance

**Comment by kozlovic** [comment] 2016-08-29 13:36
Thanks for the report, I will look into this.

**Comment by kozlovic** [comment] 2016-08-29 15:55
I was not able to reproduce the issue you reported. If I set a durable name and `MaxInFlight(1)` and in the message callback transfer the message to an ack channel from which I dequeue the message, sleep and then ack the message, I see that message arrive one by one, waiting for the ack. Would you have a test case to reproduce it? Which server version are you using?

I did find an issue though, that would prevent a durable to reconnect if the server (with file store) had been restarted. I have a PR pending for that: https://github.com/nats-io/nats-streaming-server/pull/147

Thanks.

**Comment by kozlovic** [comment] 2016-09-12 20:23
I am closing the issue now. If you still have an issue, please update and I will re-open it. Thanks!

**Closed by kozlovic** 2016-09-12 20:23 UTC
