### ISSUE TITLE
panic: lost store lock, aborting

### ISSUE THREAD

**Issue by wutkemtt** [nats-io/nats-streaming-server#1082] opened 2020-08-20 12:35 UTC
We have a pair of STAN pods running as failover in an Azure AKS cluster. As store we use a Postgres database v9.6 provided as a service by Azure. Recently we saw some pod restarts and checked the logs. 

Standby Pod:
`[1] 2020/08/19 15:29:16.141534 [INF] STREAM: Starting nats-streaming-server[nats_cluster] version 0.18.0
[1] 2020/08/19 15:29:16.141563 [INF] STREAM: ServerID: i65NxVOCvV1Deqx2npt4DV
[1] 2020/08/19 15:29:16.141565 [INF] STREAM: Go version: go1.14.4
[1] 2020/08/19 15:29:16.141567 [INF] STREAM: Git commit: [026e3a6]
[1] 2020/08/19 15:29:16.390637 [INF] STREAM: Starting in standby mode
[1] 2020/08/19 15:29:19.068403 [INF] STREAM: ft: unable to get store lock at this time, going back to standby
[1] 2020/08/19 15:30:56.195763 [INF] STREAM: Server is active
[1] 2020/08/19 15:30:56.195986 [INF] STREAM: Recovering the state...
panic: ft: serverID "d4iRyFfHnkfG6whrnoTMKp" claims to be active, aborting

goroutine 234 [running]:
github.com/nats-io/nats-streaming-server/server.(*StanServer).ftSendHBLoop(0xc0001b8600, 0xbfc76f4c0bab0d1c, 0x174bde336a, 0x12f80e0)
        /home/travis/gopath/src/github.com/nats-io/nats-streaming-server/server/ft.go:170 +0x813
github.com/nats-io/nats-streaming-server/server.(*StanServer).ftStart.func1()
        /home/travis/gopath/src/github.com/nats-io/nats-streaming-server/server/ft.go:98 +0x45
created by github.com/nats-io/nats-streaming-server/server.(*StanServer).startGoRoutine
        /home/travis/gopath/src/github.com/nats-io/nats-streaming-server/server/server.go:5471 +0x87`

Active Pod:
`[1] 2020/08/19 15:29:12.658705 [INF] STREAM: Starting nats-streaming-server[nats_cluster] version 0.18.0
[1] 2020/08/19 15:29:12.658758 [INF] STREAM: ServerID: d4iRyFfHnkfG6whrnoTMKp
[1] 2020/08/19 15:29:12.658762 [INF] STREAM: Go version: go1.14.4
[1] 2020/08/19 15:29:12.658764 [INF] STREAM: Git commit: [026e3a6]
[1] 2020/08/19 15:29:13.011658 [INF] STREAM: Starting in standby mode
[1] 2020/08/19 15:29:18.692581 [INF] STREAM: Server is active
[1] 2020/08/19 15:29:18.692876 [INF] STREAM: Recovering the state...
[1] 2020/08/19 15:29:42.925945 [INF] STREAM: Recovered 38 channel(s)
[1] 2020/08/19 15:29:42.927347 [DBG] STREAM: Channel "TestSample" delete timer set to fire in 168h0m0s
[1] 2020/08/19 15:29:42.927542 [DBG] STREAM: Channel "machine.equipmentstate" delete timer set to fire in 168h0m0s
[1] 2020/08/19 15:29:42.927765 [DBG] STREAM: Channel "dps.eu.maqs.partmeasurementv01" delete timer set to fire in 168h0m0s
[1] 2020/08/19 15:29:42.927803 [DBG] STREAM: Discover subject:           _STAN.discover.nats_cluster
[1] 2020/08/19 15:29:42.927811 [DBG] STREAM: Publish subject:            _STAN.pub.nats_cluster.>
[1] 2020/08/19 15:29:42.927814 [DBG] STREAM: Subscribe subject:          _STAN.sub.nats_cluster
[1] 2020/08/19 15:29:42.927832 [DBG] STREAM: Subscription Close subject: _STAN.subclose.nats_cluster
[1] 2020/08/19 15:29:42.927836 [DBG] STREAM: Unsubscribe subject:        _STAN.unsub.nats_cluster
[1] 2020/08/19 15:29:42.927838 [DBG] STREAM: Close subject:              _STAN.close.nats_cluster
[1] 2020/08/19 15:29:42.932552 [INF] STREAM: Message store is SQL
[1] 2020/08/19 15:29:42.932598 [INF] STREAM: ---------- Store Limits ----------
[1] 2020/08/19 15:29:42.932601 [INF] STREAM: Channels:            unlimited
[1] 2020/08/19 15:29:42.932603 [INF] STREAM: --------- Channels Limits --------
[1] 2020/08/19 15:29:42.932605 [INF] STREAM:   Subscriptions:           200
[1] 2020/08/19 15:29:42.932680 [INF] STREAM:   Messages     :     unlimited
[1] 2020/08/19 15:29:42.934463 [INF] STREAM:   Bytes        :     unlimited
[1] 2020/08/19 15:29:42.934478 [INF] STREAM:   Age          :      720h0m0s
[1] 2020/08/19 15:29:42.934481 [INF] STREAM:   Inactivity   :      168h0m0s
[1] 2020/08/19 15:29:42.934483 [INF] STREAM: -------- List of Channels --------
[1] 2020/08/19 15:29:42.934485 [INF] STREAM: TestLimit
[1] 2020/08/19 15:29:42.934487 [INF] STREAM:  |-> Subscriptions              1
[1] 2020/08/19 15:29:42.934489 [INF] STREAM:  |-> Age                     1m0s
[1] 2020/08/19 15:29:42.934490 [INF] STREAM:  |-> Inactivity              5m0s
[1] 2020/08/19 15:29:42.934492 [INF] STREAM: ----------------------------------
[1] 2020/08/19 15:29:42.934494 [INF] STREAM: Streaming Server is ready
[1] 2020/08/19 15:30:56.193315 [ERR] STREAM: ft: serverID "i65NxVOCvV1Deqx2npt4DV" claims to be active
panic: lost store lock, aborting

goroutine 73 [running]:
github.com/nats-io/nats-streaming-server/stores.(*SQLStore).updateDBLock(0xc0002140c0)
        /home/travis/gopath/src/github.com/nats-io/nats-streaming-server/stores/sqlstore.go:528 +0x377
created by github.com/nats-io/nats-streaming-server/stores.(*SQLStore).GetExclusiveLock
        /home/travis/gopath/src/github.com/nats-io/nats-streaming-server/stores/sqlstore.go:495 +0x187`

It seems, the standby pod tried to get the store log while the active pod was still there. 
Could this happen during some latency in the connection to the Postgres database? 
Is there a configuration option to optimize the intervall for checking the store lock?
Should we migrate to a more recent version of Postgres ?

**Comment by kozlovic** [comment] 2020-08-20 19:34
So I run a few tests. The way I can reproduce this (and is unfortunately expected behavior) is if I "pause" the active server so it does not update the DB lock table. I have added extra logging that is not part of the current release, which I may actually include to help explain what happens. Here is the output of active server:
```
[68050] 2020/08/20 13:25:40.919190 [INF] STREAM: Starting nats-streaming-server[test-cluster] version 0.18.0
[68050] 2020/08/20 13:25:40.919236 [INF] STREAM: ServerID: mbaxSV3hEDwdgbrhtVYmbW
[68050] 2020/08/20 13:25:40.919238 [INF] STREAM: Go version: go1.14.7
[68050] 2020/08/20 13:25:40.919239 [INF] STREAM: Git commit: [not set]
[68050] 2020/08/20 13:25:40.931524 [INF] STREAM: Starting in standby mode
[68050] 2020/08/20 13:25:42.287254 [INF] STREAM: Attempting to acquire DB lock
[68050] 2020/08/20 13:25:42.290922 [INF] STREAM: DB lock acquired
[68050] 2020/08/20 13:25:42.290938 [INF] STREAM: Server is active
[68050] 2020/08/20 13:25:42.290958 [INF] STREAM: Recovering the state...
[68050] 2020/08/20 13:25:42.308154 [INF] STREAM: Recovered 7 channel(s)
[68050] 2020/08/20 13:25:42.308346 [INF] STREAM: Message store is SQL
[68050] 2020/08/20 13:25:42.308386 [INF] STREAM: ---------- Store Limits ----------
[68050] 2020/08/20 13:25:42.308388 [INF] STREAM: Channels:                  100 *
[68050] 2020/08/20 13:25:42.308389 [INF] STREAM: --------- Channels Limits --------
[68050] 2020/08/20 13:25:42.308412 [INF] STREAM:   Subscriptions:          1000 *
[68050] 2020/08/20 13:25:42.308413 [INF] STREAM:   Messages     :       1000000 *
[68050] 2020/08/20 13:25:42.308414 [INF] STREAM:   Bytes        :     976.56 MB *
[68050] 2020/08/20 13:25:42.308415 [INF] STREAM:   Age          :     unlimited *
[68050] 2020/08/20 13:25:42.308416 [INF] STREAM:   Inactivity   :     unlimited *
[68050] 2020/08/20 13:25:42.308417 [INF] STREAM: ----------------------------------
[68050] 2020/08/20 13:25:42.308418 [INF] STREAM: Streaming Server is ready
```
In the meantime, the second starts and act as a standby:
```
[68053] 2020/08/20 13:25:44.062558 [INF] STREAM: Starting nats-streaming-server[test-cluster] version 0.18.0
[68053] 2020/08/20 13:25:44.062605 [INF] STREAM: ServerID: 08RErEhm4eLaBMFCRJr7Fj
[68053] 2020/08/20 13:25:44.062607 [INF] STREAM: Go version: go1.14.7
[68053] 2020/08/20 13:25:44.062608 [INF] STREAM: Git commit: [not set]
[68053] 2020/08/20 13:25:44.074918 [INF] STREAM: Starting in standby mode
```
Now I ctrl+z the active server:
```
^Z
[1]+  Stopped                 nats-streaming-server -store sql -sql_driver postgres -sql_source "dbname=nss_db sslmode=disable" -ft_group ft -ns nats://localhost:4222
```
Due to the lack of hearbeats, we see the second server attempts to get the DB lock, fails, but repeat until it detects that the DB lock is not being updated and therefore steals it:
```
[68053] 2020/08/20 13:25:50.640836 [INF] STREAM: Attempting to acquire DB lock
[68053] 2020/08/20 13:25:50.647579 [WRN] STREAM: Did not acquire the DB lock, trying again...
[68053] 2020/08/20 13:25:52.149639 [INF] STREAM: Attempting to acquire DB lock (1/3)
[68053] 2020/08/20 13:25:52.155686 [WRN] STREAM: DB Lock from activer server still not updated (tick=8)
[68053] 2020/08/20 13:25:53.659179 [INF] STREAM: Attempting to acquire DB lock (2/3)
[68053] 2020/08/20 13:25:53.665194 [WRN] STREAM: DB Lock from activer server still not updated (tick=8)
[68053] 2020/08/20 13:25:55.165839 [INF] STREAM: Attempting to acquire DB lock (3/3)
[68053] 2020/08/20 13:25:55.171990 [WRN] STREAM: DB Lock from activer server still not updated (tick=8)
[68053] 2020/08/20 13:25:55.172002 [WRN] STREAM: Attempting to steal DB lock, previous active server presumed not running
[68053] 2020/08/20 13:25:55.172895 [INF] STREAM: DB lock acquired
[68053] 2020/08/20 13:25:55.172903 [INF] STREAM: Server is active
[68053] 2020/08/20 13:25:55.172909 [INF] STREAM: Recovering the state...
[68053] 2020/08/20 13:25:55.191820 [INF] STREAM: Recovered 7 channel(s)
[68053] 2020/08/20 13:25:55.192028 [INF] STREAM: Message store is SQL
[68053] 2020/08/20 13:25:55.192090 [INF] STREAM: ---------- Store Limits ----------
[68053] 2020/08/20 13:25:55.192093 [INF] STREAM: Channels:                  100 *
[68053] 2020/08/20 13:25:55.192094 [INF] STREAM: --------- Channels Limits --------
[68053] 2020/08/20 13:25:55.192095 [INF] STREAM:   Subscriptions:          1000 *
[68053] 2020/08/20 13:25:55.192096 [INF] STREAM:   Messages     :       1000000 *
[68053] 2020/08/20 13:25:55.192097 [INF] STREAM:   Bytes        :     976.56 MB *
[68053] 2020/08/20 13:25:55.192113 [INF] STREAM:   Age          :     unlimited *
[68053] 2020/08/20 13:25:55.192114 [INF] STREAM:   Inactivity   :     unlimited *
[68053] 2020/08/20 13:25:55.192115 [INF] STREAM: ----------------------------------
[68053] 2020/08/20 13:25:55.192116 [INF] STREAM: Streaming Server is ready
```
After that, I un-pause the active server, then I get the panic from both side, The first server:
```
$ fg
nats-streaming-server -store sql -sql_driver postgres -sql_source "dbname=nss_db sslmode=disable" -ft_group ft -ns nats://localhost:4222
[68050] 2020/08/20 13:26:02.011718 [ERR] STREAM: ft: serverID "08RErEhm4eLaBMFCRJr7Fj" claims to be active
panic: lost store lock, aborting

goroutine 72 [running]:
github.com/nats-io/nats-streaming-server/stores.(*SQLStore).updateDBLock(0xc000280000)
	/Users/ivan/dev/go/src/github.com/nats-io/nats-streaming-server/stores/sqlstore.go:536 +0x377
created by github.com/nats-io/nats-streaming-server/stores.(*SQLStore).GetExclusiveLock
	/Users/ivan/dev/go/src/github.com/nats-io/nats-streaming-server/stores/sqlstore.go:503 +0x34c
```
and the second:
```
panic: ft: serverID "mbaxSV3hEDwdgbrhtVYmbW" claims to be active, aborting

goroutine 66 [running]:
github.com/nats-io/nats-streaming-server/server.(*StanServer).ftSendHBLoop(0xc0000f6600, 0xbfc7d170ca4e4a58, 0x2965f4e50, 0x1f060a0)
	/Users/ivan/dev/go/src/github.com/nats-io/nats-streaming-server/server/ft.go:170 +0x813
github.com/nats-io/nats-streaming-server/server.(*StanServer).ftStart.func1()
	/Users/ivan/dev/go/src/github.com/nats-io/nats-streaming-server/server/ft.go:98 +0x45
created by github.com/nats-io/nats-streaming-server/server.(*StanServer).startGoRoutine
	/Users/ivan/dev/go/src/github.com/nats-io/nats-streaming-server/server/server.go:5471 +0x87
```

Probably this is what we would have seen in your case. Adding the tracing will obviously not "fix" anything but would likely make it more obvious what happened.

**Comment by kozlovic** [comment] 2020-08-20 21:20
I have looked at this more, and to me the explanation is that there was some kind of network partition (but not a failure that would have caused TCP connection to be reported as broken) that caused streaming FT heartbeats to be missed and the standby be able to acquire the lock due to the lack of DB lock updates from the active server. In other words, the active was network partitioned from the other server AND the DB file, but without the TCP connections actually failing. As soon as it restored, the flow of FT heartbeat made the standby-now-active server fail and the previous active to also fail when detecting that it was not holding the DB lock when trying to updated it.

**Comment by wutkemtt** [comment] 2020-08-28 05:37
Sorry for my late answer. 
Okay, as I understand, a network related connection failure/problem caused this, as the active streaming server was not able to update the lock in time. So this is okay as Kubernetes can handle this for us. Thanks for having a look into this problem to exclude that there is a problem in nats-streaming.

**Comment by kozlovic** [comment] 2020-08-28 15:07
@wutkemtt Thanks, closing this now.

**Closed by kozlovic** 2020-08-28 15:07 UTC
