### ISSUE TITLE
Error during expiration: wrong sequence, wanted 5665328 got 5665327 | Big raft.log files

### ISSUE THREAD

**Issue by PBug90** [nats-io/nats-streaming-server#928] opened 2019-09-03 14:56 UTC
Running latest nats-streaming version in a clustered configuration with 3 nodes, using individual file stores for persistence.

The cluster appears to be running fine and handles incoming messages.

Nevertheless I can see the following output on the console and the raft.log files are becoming increasingly big, up to 1GB:

```
[1] 2019/09/03 14:50:06.133490 [ERR] STREAM: Error during expiration: wrong sequence, wanted 5665328 got 5665327
[1] 2019/09/03 14:50:01.126819 [ERR] STREAM: Error during expiration: wrong sequence, wanted 5665328 got 5665327
[1] 2019/09/03 14:49:56.120570 [ERR] STREAM: Error during expiration: wrong sequence, wanted 5665328 got 5665327
```

Any idea what causes this?

**Comment by kozlovic** [comment] 2019-09-03 15:36
This error means that we expect a record in a specific location in the index file to contain information about a record for that sequence, but the sequence found in the index file does not match the expected sequence. 
Do you know if this happens in all nodes? Have you tried restarting this node to see if that clears the problem? If it is a bug off-by-one that happens at runtime, restarting may resolve this. If there is something wrong in the index files, those could be removed and will be reconstructed based on the data files.

**Comment by PBug90** [comment] 2019-09-03 15:45
I tried restarting but the error persists. It appears in logs of every cluster node, the numbers vary though.

You mentioned index files - are those files with the .idx extension?
Is it safe to remove those files on a single node, then restarting it? 
Also, is it safe to remove all index files for every node?

Whats the reason for growing raft.log files? Is that a consequence of the error mentioned above?

**Comment by kozlovic** [comment] 2019-09-03 16:09
> You mentioned index files - are those files with the .idx extension?

Yes.

> Is it safe to remove those files on a single node, then restarting it?

Well, stop the node, remove the index files, then restart the node. See if error persists. If not, apply same to rest of nodes.

> Also, is it safe to remove all index files for every node?

See above.

> Whats the reason for growing raft.log files? Is that a consequence of the error mentioned above?

I don't think so. All state (messages, but also connection create/close, subscriptions, etc..) is replicated through RAFT. Messages are also stored in the NATS Streaming logs (the .idx and .dat files). The fact that a message would expire and be removed from Streaming log (actually, they may not be removed because the file slice still has valid messages) would not affect that message in the RAFT log if still present. From time to time, RAFT does a raft log compaction (snapshot). When that happens, streaming server persists in the RAFT snapshot only the first/last sequence of a given channel. Then RAFT can compact the log, which means removing log entries up to the raft index when the snapshot is done (those indexes and streaming seq numbers are NOT related). RAFT underlying store is backed by etcd.io/bbolt (a bolt DB store) that is not shrinking, but free space will be reused.
The snapshot is a function of time (between 2 and 4 minutes) and an internal threshold used in RAFT to avoid snapshot if number of entries at the time of the snapshot is less than this number (8,192 entries), and finally the number of trailing logs that is configured to keep after a snapshot (we default it to 10,240 entries). Keep in mind that a RAFT log entry does not equal a streaming message, or connection create, etc.. Several events can be combined in a single RAFT log entry.

**Comment by PBug90** [comment] 2019-09-04 07:17
I shut down one instance, deleted all of its .idx files, restarted it but the error still persists. Next step for me would be to shut down other instances and remove their index files aswell, but you stated above that this would be the next step IF the error did not persist, but it does. 

Any other suggestions or is shutting down every cluster instance at the same time, then removing their individual index files and then restarting all cluster instances to see if the error still occurs the way to go here?

**Comment by kozlovic** [comment] 2019-09-04 15:38
If you have removed index files for a given node and restarted and still it complains of the same issue, it probably mean that the gap exists in the data file and since the index is recreated based on data file, it creates this gap (say seqs 100, 102, etc..). Which version are you using?

**Comment by PBug90** [comment] 2019-09-05 08:35
Upgraded from 0.10.2 to 0.16 two days ago.

Upgrade procedure involved shutting down cluster instances completely and step by step spinning it up again with the new version.

Also one configuration accidentally happened to use the wrong cluster name, resulting in an error. I shut down that instance and adjusted the configuration and it successfully rejoined the cluster after starting.

Soon after the error appeared for the first time.

**Comment by kozlovic** [comment] 2019-09-06 14:57
So it could be that the data file was "corrupted" (missing records) with the older release. Do you mind sharing your configuration setup? I am not sure I will be able to reproduce anything, but in case.
Also, I would want to write a tool to try to fix those index files for you, but it could be risky. If the messages were really to be expired, I could replace the missing "message sequence" entries to equal the prior record, but if there are missing seq that are replaced to point to previous message, and these messages are not yet expired that could be a problem. If your stores do not contain sensitive data, we could arrange for you to send them to me to my work email address and I would have maybe a better idea of what is wrong and how to try to fix it. Let me know, but in the meantime, I am going to work on a tool.

**Comment by kozlovic** [comment] 2019-09-07 19:49
@PBug90 Sorry for the delay and the inconvenience. More recent versions of the server would not allow a gap in sequence when storing messages. So I suspect that these gaps were created using older releases and the new v0.16.0 was not able to handle them. I have a branch that attempt to address this (https://github.com/nats-io/nats-streaming-server/pull/940). If you could build from this branch (or master when PR is merged) and see if that solves the issue you are experiencing that would be great.

**Comment by PBug90** [comment] 2019-09-07 22:24
Thank you! I really appreciate your effort and help. 

Next time I will be able to give it a try is Tuesday. Will try a build then and report back.

**Comment by PBug90** [comment] 2019-09-10 14:43
I managed to build from your branch and deploy it as a container. Every instance started successfully and printed output like the following to the console:

```
14:33:27.319154 [WRN] STREAM: Skip expiration of missing sequence 5665348 for channel "PRODUCT"
14:33:27.319165 [WRN] STREAM: Skip expiration of missing sequence 5665349 for channel "PRODUCT"
14:33:27.319173 [WRN] STREAM: Skip expiration of missing sequence 5665350 for channel "PRODUCT"
```

After some time, instances stopped printing and continued to work. I guess this is expected behaviour as it was patched.

I will keep observing and post another update tomorrow.

And besides: it would be greatly appreciated if you could also build containers for merge-requests or prereleases, so that testing and update validation on customer side can be simplified. I had to gather some information to get the build going properly and had to adjust our container build scripts in order to accomodate for the manual compilation of the branch that fixes our issue.

**Comment by kozlovic** [comment] 2019-09-10 14:58
> I will keep observing and post another update tomorrow.

Thanks, yes, current behavior looks normal.

> And besides: it would be greatly appreciated if you could also build containers for merge-requests or prereleases, so that testing and update validation on customer side can be simplified. I had to gather some information to get the build going properly and had to adjust our container build scripts in order to accomodate for the manual compilation of the branch that fixes our issue.

The problem is that we publish an official docker image (we submit a PR to https://github.com/docker-library/official-images), so this is quite involved. We could push debug/pre-release images to some other repos, but you would still have to change your deployments to pull the specific image from the that said repo.

**Comment by PBug90** [comment] 2019-09-11 11:15
I took another look at the logs and did not find any more errors or issues.

Looks like it is running stable and it handled the gaps properly.

Thank you again for your quick response and the fix.

**Comment by kozlovic** [comment] 2019-09-11 16:32
@PBug90 Thanks for the confirmation. I will likely produce a release very soon.

**Closed** 2019-09-11 16:39 UTC
