### ISSUE TITLE
pending_count > max_inflight  in cluster mode on follower

### ISSUE THREAD

**Issue by bfoxstudio** [nats-io/nats-streaming-server#934] opened 2019-09-04 14:57 UTC
We have a problem with pending_count.

- Streaming Custer 3 node. 
- Cluster with Memory store

In  **Follower** Node with configuration:

> {
>   "cluster_id": "nats_streaming_inmemory",
>   "server_id": "BXJrpnh3azTvG2SoOwkbuj",
>   "version": "0.16.0",
>   "go": "go1.11.13",
>   "state": "CLUSTERED",
>   "role": "Follower",
>   "now": "2019-09-04T14:43:10.955781714Z",
>   "start_time": "2019-08-27T13:50:36.428418107Z",
>   "uptime": "8d0h52m34s",
>   "clients": 46,
>   "subscriptions": 451,
>   "channels": 35,
>   "total_msgs": 71977,
>   "total_bytes": 1538264635,
>   "open_fds": 47,
>   "max_fds": 1048576
> }

In some channels pending_count > max_inflight and "is_stalled": false:

>       "name": "ch_name",
>       "msgs": 4303,
>       "bytes": 62386608,
>       "first_seq": 283550,
>       "last_seq": 287852,
>       "subscriptions": [

>  {
>           "client_id": "XXX_outdc_7acd952c16e4",
>           "inbox": "_INBOX.JWgyLsU6xzJzALReh0WHEH",
>           "ack_inbox": "_INBOX.rdFXILoM3MFUceJZJhD39d",
>           "queue_name": "DefaultDurable:DefaultQueueGroup",
>           "is_durable": true,
>           "is_offline": false,
>           "max_inflight": 4,
>           "ack_wait": 95,
>           "last_sent": 287852,
>           "pending_count": 7,
>           "is_stalled": false
>         },
>         {
>           "client_id": "XXX_outdc_94d9f4f2fddd",
>           "inbox": "_INBOX.VIPhHToVSGxaBr7wHwQ0AV",
>           "ack_inbox": "_INBOX.rdFXILoM3MFUceJZJhD1a1",
>           "queue_name": "DefaultDurable:DefaultQueueGroup",
>           "is_durable": true,
>           "is_offline": false,
>           "max_inflight": 4,
>           "ack_wait": 95,
>           "last_sent": 287851,
>           "pending_count": 14,
>           "is_stalled": false
>         },
>         {
>           "client_id": "XXX_outdc_97e6b90e7882",
>           "inbox": "_INBOX.iYHEbMRbdrlkdSXhgdiyH8",
>           "ack_inbox": "_INBOX.rdFXILoM3MFUceJZJhDBPp",
>           "queue_name": 
>           "queue_name": "DefaultDurable:DefaultQueueGroup",
>           "is_durable": true,
>           "is_offline": false,
>           "max_inflight": 4,
>           "ack_wait": 95,
>           "last_sent": 287850,
>           "pending_count": 1,
>           "is_stalled": false
>         },

In Leader node 

>  {
>           "client_id": "XXX_outdc_7acd952c16e4",
>           "inbox": "_INBOX.JWgyLsU6xzJzALReh0WHEH",
>           "ack_inbox": "_INBOX.rdFXILoM3MFUceJZJhD39d",
>           "queue_name": 
>           "queue_name": "DefaultDurable:DefaultQueueGroup",
>           "is_durable": true,
>           "is_offline": false,
>           "max_inflight": 4,
>           "ack_wait": 95,
>           "last_sent": 287852,
>           "pending_count": 2,
>           "is_stalled": false
>         },
>         {
>           "client_id": "XXX__outdc_97e6b90e7882",
>           "inbox": "_INBOX.iYHEbMRbdrlkdSXhgdiyH8",
>           "ack_inbox": "_INBOX.rdFXILoM3MFUceJZJhDBPp",
>           "queue_name": "DefaultDurable:DefaultQueueGroup",
>           "is_durable": true,
>           "is_offline": false,
>           "max_inflight": 4,
>           "ack_wait": 95,
>           "last_sent": 287850,
>           "pending_count": 0,
>           "is_stalled": false
>         },
>         {
>           "client_id": "XXX_outdc_94d9f4f2fddd",
>           "inbox": "_INBOX.VIPhHToVSGxaBr7wHwQ0AV",
>           "ack_inbox": "_INBOX.rdFXILoM3MFUceJZJhD1a1",
>           "queue_name": "DefaultDurable:DefaultQueueGroup",
>           "is_durable": true,
>           "is_offline": false,
>           "max_inflight": 4,
>           "ack_wait": 95,
>           "last_sent": 287851,
>           "pending_count": 1,
>           "is_stalled": false
>         }

This problem is reproduced when we restart the subscribers services at high loads or mb when leader changed or when server with node and services connected to this node go to offline on 1 - 5 seconds.....
we have 2 Follower nodes with different pending_count on same subscriptions
If we stop publish new msg leader pending_count go to 0, but Follower pending_count not 0
Restart node - reset pending.

I tried to find the problem code inspection, but have not yet found.

I can’t say that everything is fine, but it seems that there is no data loss with this problem.

upd1. i restart sevice shutdown 3 client and add new 3 on same durable + queue. 
on new client pending_count: 0 and old clients deleted from cluster.  Now I am inclined that the problem is when the cluster node goes offline for a 1 - 5 seconds

**Comment by kozlovic** [comment] 2019-09-04 15:25
Which version of the server are you using? There was a question in the past (https://github.com/nats-io/nats-streaming-server/issues/861) where I explained that pending_count can be > max_inflight in case of queue subscriptions when members with unacknowledged messages are stopped. The server will redeliver to existing members causing the pending_count to possibly be > max_inflight.
Also, difference between leader and follower when messages are consumed/ack'ed is expected since the replication of messages sent/ack'ed is batched.
Are you saying that the count on a follower never goes down to 0 even when message flow stops?

**Comment by bfoxstudio** [comment] 2019-09-04 15:27
"version": "0.16.0",
"go": "go1.11.13",

**Comment by kozlovic** [comment] 2019-09-04 15:32
When node goes offline, you mean the follower? Regardless, when it comes back, the replication should resume and that offline node should receive back the log entries that it did not get while offline. But I will look with this angle in mind.

**Comment by bfoxstudio** [comment] 2019-09-04 15:33
> When node goes offline, you mean the follower? Regardless, when it comes back, the replication should resume and that offline node should receive back the log entries that it did not get while offline. But I will look with this angle in mind.

I mean the situation when in cluster follower node lost connection to leader node.

**Comment by kozlovic** [comment] 2019-09-04 15:36
> I mean the situation when in cluster follower node lost connection to leader node.

But when it gets connectivity back, the RAFT replication should be doing its job and ensure that the follower is up-to-date with regards to the replicated log. So that should not matter, meaning that the RAFT log should become consistent at some point.

**Comment by bfoxstudio** [comment] 2019-09-04 15:38
mb problem with return nil when err processReplicatedSendAndAck ?
```
	case spb.RaftOperation_SendAndAck:
		if !s.isLeader() {
			s.processReplicatedSendAndAck(op.SubSentAck)
		}
		return nil
```

**Comment by bfoxstudio** [comment] 2019-09-04 15:39
I will try to find the dependency and perform some tests to restart the nodes, but I can’t check the network loss in the current cluster

**Comment by kozlovic** [comment] 2019-09-04 15:40
processReplicatedSendAndAck() returns error only if the channel does not exists or the subscription cannot be found.

**Comment by bfoxstudio** [comment] 2019-09-04 15:52
I forgot to say 
- We use manual ack
Sometimes we have too many msgs and on all clients in queue group we have max panding_count.
Maybe a problem at this moment

**Comment by bfoxstudio** [comment] 2019-09-04 16:54
1 moment when the problem was reproduced:
1. I kill all clients in docker. with same "queue_name" and  "is_durable": true.
* Subscribe not closed not unsubscribed.
2. waited for messages to accumulate in the channels (1 minute)
3. Start 3 clients with same "queue_name" and  "is_durable": true

```
Leader
{
  "id": XXX_outdc_2ee97b7e3e31",
  "hb_inbox": "_INBOX.57VWM51l2UnQAMLmqCOA0o",
  "subscriptions": {
    "sorting_sync.transfer_box_change": [
      {
        "client_id": XXX_outdc_2ee97b7e3e31",
        "inbox": "_INBOX.57VWM51l2UnQAMLmqCOABO",
        "ack_inbox": "_INBOX.rdFXILoM3MFUceJZJhDEC1",
        "queue_name": xxx_outdc_DefaultDurable:xxx_outdc_DefaultQueueGroup",
        "is_durable": true,
        "is_offline": false,
        "max_inflight": 4,
        "ack_wait": 95,
        "last_sent": 239525,
        "pending_count": 0,
        "is_stalled": false
      }
    ]
  }
}


Node A Follower
{
  "id": XXX_outdc_2ee97b7e3e31",
  "hb_inbox": "_INBOX.57VWM51l2UnQAMLmqCOA0o",
  "subscriptions": {
    "sorting_sync.transfer_box_change": [
      {
        "client_id": XXX_outdc_2ee97b7e3e31",
        "inbox": "_INBOX.57VWM51l2UnQAMLmqCOABO",
        "ack_inbox": "_INBOX.rdFXILoM3MFUceJZJhDEC1",
        "queue_name": xxx_outdc_DefaultDurable:xxx_outdc_DefaultQueueGroup",
        "is_durable": true,
        "is_offline": false,
        "max_inflight": 4,
        "ack_wait": 95,
        "last_sent": 239525,
        "pending_count": 5,
        "is_stalled": false
      }
    ]
  }
}


Node B Follower
{
  "id": XXX_outdc_2ee97b7e3e31",
  "hb_inbox": "_INBOX.57VWM51l2UnQAMLmqCOA0o",
  "subscriptions": {
    "sorting_sync.transfer_box_change": [
      {
        "client_id": XXX_outdc_2ee97b7e3e31",
        "inbox": "_INBOX.57VWM51l2UnQAMLmqCOABO",
        "ack_inbox": "_INBOX.rdFXILoM3MFUceJZJhDEC1",
        "queue_name": xxx_outdc_DefaultDurable:xxx_outdc_DefaultQueueGroup",
        "is_durable": true,
        "is_offline": false,
        "max_inflight": 4,
        "ack_wait": 95,
        "last_sent": 239525,
        "pending_count": 10,
        "is_stalled": false
      }
    ]
  }
}
```

**Comment by kozlovic** [comment] 2019-09-04 17:06
Out of curiosity, were there pending messages (unack'ed) when you killed the consumers? Before restarting them, were their connections closed by the server due to timeout or not yet (have you modified `-hbi`, etc..)?

**Comment by kozlovic** [comment] 2019-09-04 17:51
I was able to reproduce and I think I have an idea on what's going on.

**Comment by bfoxstudio** [comment] 2019-09-05 08:12
> Out of curiosity, were there pending messages (unack'ed) when you killed the consumers? Before restarting them, were their connections closed by the server due to timeout or not yet (have you modified `-hbi`, etc..)?
No

> I was able to reproduce and I think I have an idea on what's going on.
Nice

The problem can be closed =) Thanks for the quick answers

**Closed** 2019-09-05 14:44 UTC
