### ISSUE TITLE
pending_count > max_inflight question

### ISSUE THREAD

**Issue by dpryg** [nats-io/nats-streaming-server#861] opened 2019-06-27 17:37 UTC
Hello, we are using the NATS Streaming server (v0.15.1) with the external NATS server (v2.0.0). Our cluster consists of three nodes and uses a file store. We make a request to the follower ("streaming/clientsz?subs=1") and get the response which contains this fragment:
```
{
          "client_id": "jobmgrv2-644b68cd6d-cmfnb",
          "inbox": "_INBOX.mSzSjouxoYsbW5HuHq5U8w",
          "ack_inbox": "_INBOX.OBzGfFTlPR36siKeoyltkt",
          "queue_name": "addjob-durable:jobmgr",
          "is_durable": true,
          "is_offline": false,
          "max_inflight": 50,
          "ack_wait": 300,
          "last_sent": 9218485,
          "pending_count": 136,
          "is_stalled": true
 },
```
So we can see that **pending_count > max_inflight**.
In the same time, the leader returns expected results.

Could you explain please if this is ok and why does this happen?
BTW, when we set msgs_max > 0, the number of pending messages dramatically increases.

**Comment by kozlovic** [comment] 2019-06-28 00:43
Pending count could be higher than the max_inflight in case where a member leaves and messages are reassigned to existing member(s), possibly making the count higher than max_inflight.

Not sure what you mean by "BTW, when we set msgs_max > 0, the number of pending messages dramatically increases."

Note: when trying to reproduce what you have reported, I noticed an issue (not specific to clustering) and created issue https://github.com/nats-io/nats-streaming-server/issues/862. Will have a fix soon.

**Comment by dpryg** [comment] 2019-06-28 07:24
> Pending count could be higher than the max_inflight in case where a member leaves and messages are reassigned to existing member(s), possibly making the count higher than max_inflight.

Sorry, I don't get a point.
- I send a response to the leader: pending count == max_inflight for a client.
  I send the response to the follower: pending count > max_inflight for the same client.
- I don't see any reconnections or changes in the count of clients. But even in this case, why should the server send the unacknowledged messages to the clients where a count of pending messages has already reached the limit (max_inflight)?

**Comment by kozlovic** [comment] 2019-06-28 23:02
@dpryg I cannot reproduce the situation where "pending_count > max_inflight" in none of the node (leader or follower).

What I meant about a member leaving is that all its unacknowledged messages would be reassigned to a running member, possibly making its pending count be higher than the max inflight.

You did not answer the question I had about your comment: "BTW, when we set msgs_max > 0, the number of pending messages dramatically increases.". What do you mean by that?

**Comment by dpryg** [comment] 2019-07-01 12:54
> I cannot reproduce the situation where "pending_count > max_inflight" in none of the node (leader or follower).

I can provide you with my config files and any other information if you wish.
It seems the root of the problem is just a metrics inconsistency between the leader and the followers or something like that.

> What I meant about a member leaving is that all its unacknowledged messages would be reassigned to a running member, possibly making its pending count be higher than the max inflight.

What I expect: the number of unacknowledged messages is subtracted from the number of pending messages after ack timeout is expired. After that, a server sends these messages to the clients whose max_inflight limit is not reached and increments the number of pending messages for the corresponding clients. So none client can have "pending_count > max_inflight".
I am wrong?

> You did not answer the question I had about your comment: "BTW when we set msgs_max > 0, the number of pending messages dramatically increases.". What do you mean by that?

When we set a msgs_max limit on a channel and this limit is reached, the difference in pending messages' count between the followers and the leader increases.

**Comment by kozlovic** [comment] 2019-07-01 13:37
> I can provide you with my config files and any other information if you wish.

Sure, that would be great.

> It seems the root of the problem is just a metrics inconsistency between the leader and the followers or something like that.

Probably, but still I can't reproduce it. But it is true that as long as leader's info seem correct, then I would not worry too much.

> What I expect: the number of unacknowledged messages is subtracted from the number of pending messages after ack timeout is expired. After that, a server sends these messages to the clients whose max_inflight limit is not reached and increments the number of pending messages for the corresponding clients. So none client can have "pending_count > max_inflight".
I am wrong?

When a member leaves the group and if that member has unacknowledged messages, the server MUST reassign (redeliver) them to existing members. If not, and if a server failure would occur, there would be no way of knowing that those were not acknowledged. Also, since these messages were delivered to a subscriber but clearly the subscriber won't be able to acknowledge them, it makes sense that these should be redelivered to other members of the group. 

> When we set a msgs_max limit on a channel and this limit is reached, the difference in pending messages' count between the followers and the leader increases.

Ok, will try to reproduce with this new information in mind.

**Comment by kozlovic** [comment] 2019-07-01 14:47
Set `-mm 10000` and have a queue sub running and pump messages to the system. I am checking the monitor page from a follower and never see the pending count being higher than maxInflight.

**Comment by dpryg** [comment] 2019-07-01 15:38
NATS config (3 nodes):
```
port: 4242
http_port: 8222

cluster {
  port: 4244
}

debug: false
trace: false
log_file: "/var/log/gnatsd/gnatsd.log"

max_payload: 67108864

write_deadline: "300s"
```

NATS Streaming config (same 3 nodes):
```
streaming: {
id: cerebro_v2
store: "file"
dir: "/var/lib/stan"
sd: false
sv: false
ns: "nats://xxx1:4242,nats://xxx2:4242,nats://xxx3:4242"
secure: false
limits: {
    max_msgs: 0
    max_bytes: 10GB
    max_age: "24h"
    max_inactivity: "6h"
}
cluster: {
    node_id: "n1" // n2 for 2nd node, n3 for 3rd node
    peers: [
        "n1",
        "n2",
        "n3",
    ]
    log_path: "/var/lib/stan"
}
}
```

```go
func NewInsecuredNATS(es []Endpoint, name string) (*nats.Conn, error) {
	natsLog := log.WithField("module", "nats")
	nc, err := nats.Connect(
		fmt.Sprintf("nats://%s:%s/", es[0].Host, es[0].Port),
		natsServers(es[1:], true),
		nats.MaxReconnects(-1),
		nats.ClosedHandler(func(c *nats.Conn) {
			natsLog.Info("Connection closed")
		}),
		nats.DisconnectHandler(func(c *nats.Conn) {
			natsLog.Warn("Connection broken")
		}),
		nats.ReconnectHandler(func(c *nats.Conn) {
			natsLog.Info("Connection established with ", c.ConnectedUrl())
		}),
		nats.Timeout(10*time.Second),
		nats.ReconnectBufSize(-1),
		nats.Name(name),
	)
	return nc, err
}

func NewSTAN(clusterID string, clientID string, nc *nats.Conn) (stan.Conn, error) {
	sc, err := stan.Connect(
		clusterID,
		clientID,
		stan.NatsConn(nc),
		stan.SetConnectionLostHandler(func(_ stan.Conn, err error) {
			verify.PassOrDieWithMsg(err, "Connection with NATS Streaming Server has been lost")
		}),
	)
	if err != nil {
		return nil, err
	}
	return sc, nil
}
```

```go
        nc, err := util.NewInsecuredNATS(cfg.NATS, cfg.ClientID)
	verify.PassOrDie(err)
	defer nc.Close()

	sc, err := util.NewSTAN(cfg.STANCluster, cfg.ClientID, nc)
	verify.PassOrDie(err)
	defer sc.Close()
```

```go
        _, err = sc.QueueSubscribe(
		cfg.NATSAddJob,
		queueGroupName,
		func(msg *stan.Msg) {
			// a few requests to external NATS & msg.Ack() 
		},
		stan.DurableName(cfg.NATSAddJob + "-durable"),
		stan.SetManualAckMode(),
		stan.AckWait(5 * time.Minute),
		stan.MaxInflight(50),
	)
```

Now pending_count < max_inflight, but we have the weird differences in states of the nodes (smth goes badly wrong):
[leader.txt](https://github.com/nats-io/nats-streaming-server/files/3346294/leader.txt)
[follower.txt](https://github.com/nats-io/nats-streaming-server/files/3346295/follower.txt)

**Comment by kozlovic** [comment] 2019-07-01 16:10
Thanks. There is an issue the way you configure the NATS cluster. You have each node specifying a NATS cluster section (port 4244) but are not specifying any route. This means that the servers are all disconnected to each other. 
When you specify `ns: "nats://xxx1:4242,nats://xxx2:4242,nats://xxx3:4242"`, this will work if all 3 have the same config and they will all use the first server as the single NATS server. But if that server exits, then the 2 remaining may reconnect to the second server or any other in the list and then you would end-up with servers that are not able to reach each other.

So you should have something like this instead:
```
port: 4242
http_port: 8222

cluster {
  port: 4244
  routes: [
     "nats://xxx1:4242"
     "nats://xxx2:4242"
     "nats://xxx3:4242"
  ]
}
```
then remove `ns` from the `streaming{}` config.

> Now pending_count < max_inflight, but we have the weird differences in states of the nodes (smth goes badly wrong):

What do you mean the weird differences? The replication of subscriptions' sent and ack'ed messages are asynchronous and buffered, but even if they were not, you cannot except the values to be exactly the same since these are 2 different http requests (even if you make them as close in time as possible). 

Given that your clients are using manual ack and are possibly delaying ack, I will re-run a test and see if I observe the pending_count > maxInflight.

**Comment by dpryg** [comment] 2019-07-01 17:33
> You have each node specifying a NATS cluster section (port 4244) but are not specifying any route

Oops, very sorry, I removed this accidentally (lost in the # comments) when was writing that message. Of course, I have at n2 and n3 nodes:
```
routes = [
        nats-route://xxx1:4244
    ]
```
Is that still wrong?

> What do you mean the weird differences? The replication of subscriptions' sent and ack'ed messages are asynchronous and buffered, but even if they were not, you cannot except the values to be exactly the same since these are 2 different http requests (even if you make them as close in time as possible).

Sure, but what about is_stalled field? Is it ok to have different values?
And why the leader always has values less than the followers? It ends up having many pending messages at the followers, while the leader has max_inflight at maximum.

**Comment by kozlovic** [comment] 2019-07-01 18:17
```
Oops, very sorry, I removed this accidentally (lost in the # comments) when was writing that message. Of course, I have at n2 and n3 nodes:

routes = [
        nats-route://xxx1:4244
    ]
Is that still wrong?
```
Actually in my previous post I made the mistake of using the wrong port (should have been 4244). Routes should have the URLs of the other servers (but can possibly have their but will ignore it).

> Sure, but what about is_stalled field? Is it ok to have different values?

Actually, I am surprised that it is sometimes set to `true` since it should not be updated in follower, but that means that yes, you could see a difference but that does not matter until the follower becomes leader (since only leader sends messages to subscribers).

> And why the leader always has values less than the followers?

Because things happen "realtime" in the leader, but the information that given msg seq was sent to a sub and ack'ed is replicated asynchronously to followers, hence the possible differences.

I have seen the pending_count > maxInflight as I suggested when stopping some of the subscriptions that have unacknowledged messages. This is expected however I have seen that the number of messages that are reassigned still show up in the follower's pending count even after those have been acknowledged. I am looking into this.

**Comment by kozlovic** [comment] 2019-07-22 20:40
Sorry for not updating sooner. What I had seen during some tests is that when stopping some queue member(s) that had unacknowledged messages, those were reassigned to remaining members. However, in some cases those messages were still showing as pending. This was because in some cases those messages were not redelivered right away if the member messages were reassigned to had some unacknowledged messages of its own. This has been addressed in https://github.com/nats-io/nats-streaming-server/pull/871.

With that in mind, are you still experiencing situation where pending_count is greater than max_inflight in followers *without* any queue member being stopped?

**Comment by kozlovic** [comment] 2019-08-14 15:29
Some issues about redelivery for queue members have been fixed. Closing this for now, please re-open if new information becomes available.

**Closed by kozlovic** 2019-08-14 15:29 UTC
