### ISSUE TITLE
Clustered nats-streaming reconnect graceful handling 

### ISSUE THREAD

**Issue by dxj910804** [nats-io/nats-streaming-server#733] opened 2019-01-24 23:55 UTC
This is a question on how to reconnect to the cluster gracefully, when current connection lost. 
I'm getting errors like this when trying to reconnect with the same clientID: 
 "stan: clientID already registered"
scenario is I have 3 nats-streaming server running with 3 embedded nats-servers as a cluster and one service connects to server A. When I stop server A, I'm hoping it will look for server B or C and try reconnect, but I'm getting the error mentioned above from server B. 

What's the correct way of handling this kind of situation ?

**Comment by dxj910804** [comment] 2019-01-29 23:04
Did some experiments and found that even though client was initially connected to server A, then I stop A, pingServer was still successful. However, other behaviors are unexpected and unpredictable, sometimes the message goes through fine, sometimes connection stays alive (ping successful), sometimes it just crashes. 

Kind of need an error handling suggestion in the situation that while one of the clustered server goes down.

**Comment by kozlovic** [comment] 2019-02-19 16:40
Sorry for the delay. Would need more info in order to reproduce. Assuming that your 3 NATS Streaming server are really connected to each other in full mesh, then when one of the server is stopped, the low level NATS connection should be able to reconnect to any of the other NATS servers. The pingServer function will fail only if the NATS connection is closed or if the number of PINGs without responses exceeds the configured number. You should have registered a connection lost handler with SetConnectionLostHandler() in order to be notified if the connection is permanently lost. If this callback is not invoked then it means that there is still communication with the cluster and you should not be trying to recreate the connection with the same client ID since your client is still valid, the response of the cluster that this clientID is already registered makes sense.
Keep in mind that if you stop the leader while there was a publish in progress or just before the publish, it is possible that this publish will timeout since there needs to be a new leader election.

**Comment by dxj910804** [comment] 2019-02-20 17:44
Thanks Ivan. 
You are right, the error I saw was because I added my own logic to reconnect to one of the other servers. So the only error handling I need to do is record the errors when connection finally lost, and timeout errors while election is going on for subscribe and publish.

**Comment by kozlovic** [comment] 2019-02-20 17:45
Good to hear. Closing the issue then.

**Closed by kozlovic** 2019-02-20 17:45 UTC
