### ISSUE TITLE
High memory usage & Client error "publish ack timeout" "max in flight reached"

### ISSUE THREAD

**Issue by shaiaTradair** [nats-io/nats-streaming-server#407] opened 2017-10-18 05:27 UTC
Using **Nats streaming with FILE store**, suddenly client's throw me  those errors: "publish ack timeout" "max in flight reached" (nodejs client)

Memory is growing to 16GB and up , and crash when is no more memory on the machine, nats log not showing nothing.

Any suggestions  ?

**Comment by kozlovic** [comment] 2017-10-18 14:41
Which version of the server are you using? Recent versions, when using FileStore, should have little memory footprint because the server relies on the file storage to store the messages.

Could it be that the server was blocked trying to either write to disk or do some operations and incoming messages would accumulate in the internal queue waiting for processing?

Even then, it would mean that you were publishing a lot, because even when publishing asynchronously, a publisher as a default publisher max inflight of 16,384 messages, so you would have to have many publishers or restarting the publisher many times before reaching those limits?

Please check server log for any error conditions and if this happens again, maybe the best course would be to have the server run with `-m <port number>` and then go to `http://<host>:<monitoring port>/stacksz` and collect the output. Wait a bit and repeat the operation again so we can compare 2 different captures.

**Comment by diogogmt** [comment] 2017-11-01 18:05
@kozlovic 

Also seeing the error `publish ack timeout` being alerted sporadically:

```
*errors.errorString: Error acknowledging message VjubM0CE2Dg4F1EWyRDs9e - error: stan: publish ack timeout
File "/github.com/nats-io/go-nats-streaming/stan.go", line 400, in func1
```

We are running with file store enabled and the default `MaxPubAcksInflight`.

Streaming server verison: `0.5.0`
Streaming client version: `0.3.4`


What could be the triggers for that timeout error?

Could it ever happen that the message gets delivered, processed, but then only the ack fails? In that case what are the retry/constraints set on the clients for the message acknowledgment ?

We could try to track the last message sequence that was processed to avoid re-processing messages, however, since we are running the subscribers in a queue that would require some coordination.

**Comment by kozlovic** [comment] 2017-11-01 19:13
Keep in mind that NATS Streaming clients are not directly connected to the Streaming server, so it is perfectly possible that the pub messaged was received by the server and persisted/delivered but the ack did not make it back to the publisher.

It is also possible that the published message did not get to the server at all, again, because of connectivity issues.

If your server is otherwise responsive and does not report any specific errors and pub ack timeout occurs only for some applications while other are happily working, it may just be connectivity. Otherwise, you may want to follow the trouble shooting that I have described in previous post.

**Comment by robertfreund** [comment] 2017-11-02 13:58
We are experiencing very similar issue with nats-streaming becoming unresponsive after some time under load. We are using File store for persistence.

```
"limit": 1024,
  "count": 20,
  "total": 20,
```
```
{
  "server_id": "IKH2mfmtmS5QgoyNMLRH8j",
  "version": "0.9.6",
  "go": "go1.7.6",
  "host": "0.0.0.0",
  "auth_required": false,
  "ssl_required": false,
  "tls_required": false,
  "tls_verify": false,
  "addr": "0.0.0.0",
  "max_connections": 65536,
  "ping_interval": 120000000000,
  "ping_max": 2,
  "http_host": "0.0.0.0",
  "http_port": 8222,
  "https_port": 0,
  "auth_timeout": 1,
  "max_control_line": 1024,
  "cluster": {
    "addr": "0.0.0.0",
    "cluster_port": 0,
    "auth_timeout": 1
  },
  "tls_timeout": 0.5,
  "port": 4222,
  "max_payload": 1048576,
  "start": "2017-11-02T12:57:42.242828697Z",
  "now": "2017-11-02T13:47:14.328711947Z",
  "uptime": "49m32s",
  "mem": 9011404800,
  "cores": 8,
  "cpu": 602,
  "connections": 797,
  "total_connections": 3011,
  "routes": 0,
  "remotes": 0,
  "in_msgs": 168017706,
  "out_msgs": 536416901,
  "in_bytes": 1098912825895,
  "out_bytes": 33872257686,
  "slow_consumers": 3,
  "subscriptions": 14832,
  "http_req_stats": {
    "/": 0,
    "/connz": 1187,
    "/routez": 1186,
    "/subsz": 1186,
    "/varz": 1719
  }
}
```



The following are multiple stackz outputs.
[stack_a.txt](https://github.com/nats-io/nats-streaming-server/files/1437947/stack_a.txt)
[stack_b.txt](https://github.com/nats-io/nats-streaming-server/files/1437948/stack_b.txt)
[stack_c.txt](https://github.com/nats-io/nats-streaming-server/files/1437949/stack_c.txt)

Are there additional memory tuning flags we can use to handle this better. This is currently 32GB and uses all 32GB in about 1 hour.

The nats-streaming logs do not say anything when it becomes unresponsive.

This single nats-streaming instance handles both regular gnats connections as well as streaming connections. Is this just too much work for this size of box?

**Comment by tylertreat** [comment] 2017-11-02 14:13
@robertfreund Can you try profiling the heap and see where the memory usage is coming from?

**Comment by kozlovic** [comment] 2017-11-02 15:10
@robertfreund Also, I would use dedicated gnatsd to pin-point where the issue is. You can run separate instance of nats server and use  `nats-streaming-server <your options> -ns nats://<gnatsd host>:<gnatsd port>` to connect to the NATS Server instance. The stack show a lot of activity gnatsd related, so I am not sure what the problem is.

**Comment by robertfreund** [comment] 2017-11-02 16:14
yes I will continue to investigate this. We were actually trying to consolidate our streaming / gnatsd instance. Is it possible somehow to many subscriptions for memory. I notice when using lets say "consumerGroupA" durable we will get lots of 'stan: subscribe request timeout' when it seems nothing has changed. If I modify to use "consumerGroupB" everything subscribes fine. Is some limit or some store of subscribers being exhausted.

I would note; prior to moving our stan/nats subscribers to use same nats-streaming instance we were experiencing a lot of stan: publish ack timeout guid=UIOw8blIC2x5FI2fNPTCQP errors. The thought from previous posts was to increase memory. 

I have since bumped version now as well:
Go version: go1.9.1
Starting nats-server version 1.0.4
Starting http monitor on 0.0.0.0:8222
[1] 2017/11/02 15:14:25.278022 [INF] STREAM: Message store is FILE
[1] 2017/11/02 15:14:25.278051 [INF] STREAM: ---------- Store Limits ----------
[1] 2017/11/02 15:14:25.278054 [INF] STREAM: Channels: unlimited
[1] 2017/11/02 15:14:25.278056 [INF] STREAM: --------- Channels Limits --------
[1] 2017/11/02 15:14:25.278058 [INF] STREAM: Subscriptions: unlimited
[1] 2017/11/02 15:14:25.278060 [INF] STREAM: Messages : unlimited
[1] 2017/11/02 15:14:25.278062 [INF] STREAM: Bytes : unlimited
[1] 2017/11/02 15:14:25.278064 [INF] STREAM: Age : 24h0m0s
[1] 2017/11/02 15:14:25.278066 [INF] STREAM: ----------------------------------
Im at a loss of where 32GB could be used up on a FILE store and will try memory profile. Another observation is I see my FILE store on disk is almost as large as my memory growth? 

Right now Ive been running for 58 minutes. disk is 8.6 GB / memory is 9GB. Is it possible its doing both file and memory?

**Comment by kozlovic** [comment] 2017-11-02 16:33
Have you changed to use separate NATS Server instance? I would want to see with what process the memory is associated with. Having "remote" NATS Server will easily help figure out if the bulk of memory usage is in the NATS Server part or the Streaming part.

With FileStore, messages are not kept in memory (except for short amount of time when being written). So the Streaming server should not need much memory for messages themselves. It does keep connections/subscriptions objects in memory though, so having lots of those may contribute to higher memory usage.

**Comment by robertfreund** [comment] 2017-11-02 16:37
Ok Thanks. Im in process of that on separate instance. 

I know from our previous revision though we used nats-streaming 16GB and gnatsd 16GB. Two seperate boxs. nats-streaming 100% of time would take all 16GB. gnatsd would use max 500m with our current load. 

For us it has always been nats-streaming memory. 

I am going to do some comparisons in our various environments that have different load characteristics.

**Comment by tylertreat** [comment] 2017-11-02 16:41
@kozlovic I know at one point there was a cache used for file store. Is that disabled by default now?

**Comment by kozlovic** [comment] 2017-11-02 16:48
We used to keep all stored messages in memory in older releases. Now there is a cache, but the stored message are evicted from that cache within a second. On top of that, there is a write buffer that is used to minimize disk writes. This buffer is flushed to disk when server processes a set of incoming messages (in the ioLoop). This buffer can be disabled with `-file_buffer_size 0`. But even when buffer is in use, it is shrunk when not needed. Of course, if you have tons of channels, then each channel will have a buffer, even small it could add up.

**Comment by robertfreund** [comment] 2017-11-02 17:46
I have separated streaming and nats and see same footprint. streaming disk and memory align. gnatsd uses very little memory as expected.
```
CONTAINER           CPU %               MEM USAGE / LIMIT       MEM %               NET I/O             BLOCK I/O           PIDS
nats-streaming       9.94%               3.053 GiB / 31.42 GiB   9.72%               3.14 GB / 1.3 GB    8.19 kB / 6.41 GB   0
gnatsd        136.76%             30.28 MiB / 31.42 GiB   0.09%               2.85 GB / 3.66 GB   0 B / 0 B           0
```

**Comment by kozlovic** [comment] 2017-11-02 18:42
How many channels are you using? Do you experience the same if you run outside of docker?
I have run a test with sending 10,000,000 messages to a single channel and the memory usage stays constant.

**Comment by robertfreund** [comment] 2017-11-02 19:00
We have 20 channels. 10 get heavy usage, 10 light usage - based on type of data we move on channels. Heavy usage is sustained minimum micro batch 400 second. We were never able to get individual message throughput levels much higher in nats-streaming. 
gnatsd we have minimum 25K a second sustained and have no issue.

**Comment by kozlovic** [comment] 2017-11-02 23:44
@robertfreund Quick question: how far apart were stack captures made (few seconds, within same second, ...) ?

**Comment by robertfreund** [comment] 2017-11-03 13:04
~ 60 seconds.

I will say a big noticable difference when separating the two was much lower cpu usage. The combined cpu is maybe 140% where as when running together it was constantly in the ~600% range.

Im working on memory profiling now.

**Comment by kozlovic** [comment] 2017-11-03 22:46
@robertfreund I could not make sense of the stacks because some go routines seem to be stuck trying to acquire a lock that is not found locked in any of the go routines present in the captures. I then realized that your stack captures seem to be truncated (if you go at the end of file, you would see that it seem to be not complete). If you still have server running, please get to the `stacksz` endpoint one more time (one capture is enough), but make sure this is not truncated. Thanks!

**Comment by robertfreund** [comment] 2017-11-07 21:26
My 'issue' is no issue at all. After building custom nats-streaming-server with pprof it was clear that report via docker stats is not accurate. Actual usage is sustained <~150mb.

**Comment by tylertreat** [comment] 2017-11-07 21:42
I believe Docker may be reporting page cache as memory consumed, which may lead to surprising metrics. https://github.com/moby/moby/issues/10824

**Comment by kozlovic** [comment] 2017-11-07 21:55
Good to hear. However, I still do believe that there was an issue with the stacks captures I saw, however, they were not complete and so I could not figure out what was wrong. So if you have still a chance to capture and send me the output for review, I would appreciate it.

As for pprof, there is a profiler included in gnatsd that you could have used (when running NATS Streaming with embedded gnatsd), however, I notice that we have introduced a defect preventing the use of it if the sampling is more than a write timeout of 2 seconds that was incorrectly added. I will create an issue for that.

**Comment by robertfreund** [comment] 2017-11-07 22:09
Heres the latest stackz. Note the previous was when combined. This is with gnatsd separate. 
[stackz_out.txt](https://github.com/nats-io/nats-streaming-server/files/1451843/stackz_out.txt)

Picture at time:
```
20   0 43400  37m 5592 S 137.8  0.1 217:10.49 /gnatsd                                                                                                                            
20   0  564m 139m 7932 S 11.6  0.4  13:40.27 /nats-streaming-server
```

**Comment by kozlovic** [comment] 2017-11-07 22:12
Thanks, but I no longer see the go routines with `closeClient` go routines being stuck, so you may have restarted the instance since then? If you do observer issues again, please try to get a capture (ensure that it is not truncated). Thanks!

**Comment by kozlovic** [comment] 2017-12-06 21:19
Closing for now due to age. Please re-open if you have more information.

**Closed by kozlovic** 2017-12-06 21:19 UTC
