### ISSUE TITLE
Optimization: message re-deliver is done only after missing heartbeat

### ISSUE THREAD

**Issue by ivankostov** [nats-io/nats-streaming-server#818] opened 2019-05-02 14:23 UTC
When having a queue with 2 subscribers, after "crashing" of one of them, the message is forwarded to the second subscriber after heartbeat timeout. It would be cool to have faster redistribution. As far as I understand, the reason is that the streaming server cannot detect socket disconnect, since the client is not directly connected. Is it possible ( does it make sense ) to extend the NATS server to  post a message on predefined topic ( for example "__disconnected__clients" ) ? In this case the streaming server would not need to wait for a heartbeat timeout.

Thank you in advance,
Ivan

**Comment by kozlovic** [comment] 2019-05-02 15:32
Have you considered lowering the server-to-client heartbeats to your satisfaction? 
Look for `hb_interval` in the README.md or `-hbi` (and the 2 others) in the command line help.

**Comment by ivankostov** [comment] 2019-05-02 15:48
Hi Ivan ;),

the problem is that you cannot set the timeout below the average job
duration. If you have jobs that take up to 15 sec
you cannot set it to 1sec. What do you think about the proposed idea? Is it
feasible ? I could help with the implentation.

Cheers,
Ivan


На чт, 2 май 2019 г., 17:32 Ivan Kozlovic <notifications@github.com> написа:

**Comment by kozlovic** [comment] 2019-05-02 15:52
I like your first name ;-)

I was referring to server to client heartbeats. Server sends heartbeats at defined interval and library is echoing back (regardless what your application is doing). So you could have server-to-client HB every second and still have a job that needs 15 sec and server would still be fine. Only when the library fails to respond to heartbeat (that is, if you app crashes - or is network partitioned) that it will then consider the connection lost (after the (hbi+hbt)*hbf time). 

The problem is that if you are using queue subs and run in clustering mode, at the moment, the server does not redeliver a message to any other member (until the member is completely removed). I am trying to change that.

**Comment by ivankostov** [comment] 2019-05-02 16:00
Cool,I will try it out.

На чт, 2 май 2019 г., 17:53 Ivan Kozlovic <notifications@github.com> написа:

**Comment by kozlovic** [comment] 2019-05-14 20:20
Closing for now.. will re-open if needed.

**Closed** 2019-05-14 20:21 UTC
