### ISSUE TITLE
at 1 million messages in a queue, subscribers can get stuck.

### ISSUE THREAD

**Issue by ssoroka** [nats-io/nats-streaming-server#800] opened 2019-04-14 20:18 UTC
I've had some trouble with subscribers being able to read a messages off a queue once they pass the 1 million messages in queue mark. The only way I've found to fix this behavior is to rename the queue and start over with an empty queue. Restarting the cluster and clients has no effect. Subscribers are not able to resume reading messages in queue, and are blocked from reading new ones.

**Comment by kozlovic** [comment] 2019-04-14 22:37
If you could describe exactly what the problem is? Do you have a setup that reproduces this issue? Maybe also share your configuration file?

**Comment by derekcollison** [comment] 2019-04-15 22:07
This is a configuration item in my opinion. The server will be configured to limit by maximum messages or maximum bytes to store. I would imagine the message limit for the server you are running is 1M.

**Comment by kozlovic** [comment] 2019-04-29 20:51
Are you using message expiration? If so, it could be that you were affected by issue resolved in PR #801 (issue #795). One way to check is that if you have monitoring port enabled, `/channelsz?channel=<name>&subs=1` would show that the subscription's `last_sent` is higher than the channel's `last_seq`.

**Comment by ssoroka** [comment] 2019-07-18 18:06
No, I don't believe we were. Sorry I couldn't be more help here.

**Comment by kozlovic** [comment] 2019-07-18 18:08
@ssoroka No worries. Are you still experiencing the issue? What version of server and what client lib/version are you using? If this is no longer an issue, please let me know and I will close the issue.

**Comment by kozlovic** [comment] 2019-08-14 15:28
Closing for now, please re-open if new info is available.

**Closed by kozlovic** 2019-08-14 15:28 UTC
