### ISSUE TITLE
Is NATS streaming server suitable for massive data transfer?

### ISSUE THREAD

**Issue by luxl** [nats-io/nats-streaming-server#634] opened 2018-08-03 08:53 UTC
For example:
   I have a service that will acquire data from hardware continuously and also send these data to another place in order to store the data. The data acquisition rate can be up to 80MB/s and the acquisition time can be hours. Can NATS handle this situation?

**Comment by jacktuck** [comment] 2018-08-03 11:22
That's a vague question. What does your setup look like - how many nodes?

**Comment by kozlovic** [comment] 2018-08-08 22:28
As @jacktuck pointed out, this is a bit vague. Are you running standalone, or in clustering mode? How many nodes in the cluster? What persistent store are you using (file store, SQL)? How many producers? Are there lots of subscriptions receiving those messages?

Also, even with all answers to above questions, I would recommend you to try it for yourself. Setting up a server and running some clients is pretty easy.

**Comment by luxl** [comment] 2018-08-09 01:49
sorry for the late response.
I'm running in clustering, but not many nodes, only serval nodes. Only one producer(node) and one node will receive these data and then store them in a file.

**Comment by kozlovic** [comment] 2018-08-09 14:57
I am confused. What are you referring to node? Myself, by node I meant a NATS Streaming Server (nats-streaming-server executable) participating in the cluster.

And what do you mean "receive these data and then store them in a file"? This is what nats streaming is doing, so I am confused.

If I were you, I would run a test with the type of data/rate that you are expecting, on the machines you are planning to run the cluster in, and see if performance is where you want it to be.

**Comment by kozlovic** [comment] 2018-08-31 19:32
@luxl Any update on this?

**Comment by ivanrodolfo** [comment] 2018-11-07 13:18
Hi, about nats stream massive usage. 

I don't know if it is right to use this topic, so let me know if it is wrong place to talk about this, ok?

I have 2 use cases, in the first case it works fine, but when a change to the second case I start to have some issues on nats stream, maybe I doing something wrong. So I want to share my use cases here:

My first use case

I using a Nats stream in a cluster mode (3 pods of nats and also 3 pods of stream). Using disk to persist messages (forever persistence). The number of messages I receive here is less then 200k per day and size variation is something between 256bytes and 1kb. The messages are persisted in only 2 different subjects with 2 producers and 2 consumers on subjects.
   
Nats stream works fine in this scenario for for some weeks.

So, I change this scenario to my second scenario.

Instead of 2 subjects, now I using 8 different subjects with 2 different producers per subject.
The total amount of messages per day now is between 1.2 and 1.6MM per day (it is 4x more then the first scenario).


But it this second, after about 30 hours, my master pod (leader) of stream has exhausted with high memory usage and stop working, changing this master to another pod.

Is there any thing that I can do to prevent this memory usage in nats stream pod? 
When the master pod of stream changes, my clients are not receiving any sign that notify them that they need to reconnect on stream. Is it necessary, or maybe my ConnectionLostHandler is not working fine. But I don't know.

I thing my use case is not a massive use at all but I trying to understand what I doing wrong!

**Comment by kozlovic** [comment] 2018-11-08 00:02
No, I would not consider this massive.
Which version of streaming and nats servers are you running? You are using different pods for streaming and nats, right?

Could you run the streaming server with `-m <port>` to enable monitoring? Would be interesting to see the `http://<host>:8222/varz` result for memory usage, then `http://<host>:8222/streaming/serverz` and `http://<host>:8222/streaming/channelsz?subs=1`.

Note that since you connect streaming to nats server), the monitoring page `http://<host>:8222` will not display much (like connz, etc) since that part is not handled by the streaming server but the NATS server. Still, varz should contain some info.

**Comment by ivanrodolfo** [comment] 2018-11-09 15:31
Kozlovic,
I'm investigating more about the problem, I looking into logs of my apps to understand this behaviour.  I'm sending here more information about my cluster.

 
Nats Streaming:
nats-streaming-server version 0.11.2
Go version: go1.11.1
 Startup

 args:
        - -cid
        - cluster_id
        - --cluster_sync=false
        - --file_sync=false
        - -m
        - "8222"
        - -ns
        - nats://user_name:password@nats-service:4222
        - -mc
        - "0"
        - -msu
        - "0"
        - -mm
        - "0"
        - -mb
        - "0"
        - -ma
        - "0"
        - -hbi
        - 30s
        - -hbt
        - 10s
        - -hbf
        - "330"
        - --store
        - file
        - --dir
        - /nats/nss
        - --file_buffer_size
        - "2097152"
        - --file_slice_max_msgs
        - "0"
        - --file_slice_max_bytes
        - "0"
        - --file_slice_max_age
        - "0"
        - --file_fds_limit
        - "0"
        - --file_parallel_recovery
        - "1"
        - --ft_group
        - ft-nats-tt
resources:
 cpu: 900m
 memory: 1Gi

Replicas: 3

——-
http://localhost:8222/streaming/channelsz?subs=1
{
  "cluster_id": "nats-ff",
  "server_id": "pHZHSsQYFfWbOdvQ83rCE9",
  "now": "2018-11-09T15:05:47.946606971Z",
  "offset": 0,
  "limit": 1024,
  "count": 10,
  "total": 10,
  "channels": [
    {
      "name": "subject1",
      "msgs": 1,
      "bytes": 347,
      "first_seq": 1,
      "last_seq": 1
    },
    {
      "name": "subject2",
      "msgs": 83778,
      "bytes": 27786074,
      "first_seq": 1,
      "last_seq": 83778
    },
    {
      "name": "subject3",
      "msgs": 226695,
      "bytes": 64194659,
      "first_seq": 1,
      "last_seq": 226695
    },
    {
      "name": "subject4",
      "msgs": 4,
      "bytes": 1396,
      "first_seq": 1,
      "last_seq": 4
    },
    {
      "name": "subject5",
      "msgs": 1758393,
      "bytes": 587725595,
      "first_seq": 1,
      "last_seq": 1758393
    },
    {
      "name": "subject6",
      "msgs": 5145414,
      "bytes": 1457576281,
      "first_seq": 1,
      "last_seq": 5145414
    },
    {
      "name": "subject7",
      "msgs": 114163,
      "bytes": 37868215,
      "first_seq": 1,
      "last_seq": 114163,
      "subscriptions": [
        {
          "client_id": "1b122e37-e9a5-42b0-8345-a263f427c08e",
          "inbox": "_INBOX.QTBteImsBa7j0VAe9ebGKU",
          "ack_inbox": "_INBOX.pHZHSsQYFfWbOdvQ8BT8wz",
          "is_durable": false,
          "is_offline": false,
          "max_inflight": 1,
          "ack_wait": 30,
          "last_sent": 114163,
          "pending_count": 0,
          "is_stalled": false
        }
      ]
    },
    {
      "name": "subject8",
      "msgs": 573563,
      "bytes": 162607370,
      "first_seq": 1,
      "last_seq": 573563
    },
    {
      "name": "subject9",
      "msgs": 80015,
      "bytes": 26377770,
      "first_seq": 1,
      "last_seq": 80015
    },
    {
      "name": "subject10",
      "msgs": 239321,
      "bytes": 68367543,
      "first_seq": 1,
      "last_seq": 239321
    }
  ]
}
————
http://localhost:8222/streaming/serverz
{
  "cluster_id": "nats-ff",
  "server_id": "pHZHSsQYFfWbOdvQ83rCE9",
  "version": "0.11.2",
  "go": "go1.11.1",
  "state": "FT_ACTIVE",
  "now": "2018-11-09T15:07:00.821198912Z",
  "start_time": "2018-10-29T19:51:38.609402607Z",
  "uptime": "10d19h15m22s",
  "clients": 12,
  "subscriptions": 14,
  "channels": 10,
  "total_msgs": 8221435,
  "total_bytes": 2432534475
}
————
Nats Server:
nats-server version 1.3.0
Go version: go1.11.1

Startup args:
        - -m
        - "8222"
        - --cluster
        - nats://0.0.0.0:6222
        - --routes
        - nats://nats-service:6222


Replicas: 3

——-

http://localhost:8222/varz

 {

  "server_id": "TMGnlp10JrKj6zzU97X8Y4",
  "version": "1.3.0",
  "proto": 1,
  "git_commit": "eed4fbc",
  "go": "go1.11",
  "host": "0.0.0.0",
  "connect_urls": [
    "10.0.6.67:4222",
    "10.0.0.173:4222",
    "10.0.0.197:4222"
  ],
  "addr": "0.0.0.0",
  "max_connections": 65536,
  "ping_interval": 120000000000,
  "ping_max": 2,
  "http_host": "0.0.0.0",
  "http_port": 8222,
  "https_port": 0,
  "auth_timeout": 1,
  "max_control_line": 1024,
  "cluster": {
    "addr": "0.0.0.0",
    "cluster_port": 6222,
    "auth_timeout": 1
  },
  "tls_timeout": 0.5,
  "port": 4222,
  "max_payload": 1048576,
  "start": "2018-11-07T11:53:41.222229141Z",
  "now": "2018-11-09T15:07:49.892738642Z",
  "uptime": "2d3h14m8s",
  "mem": 13500416,
  "cores": 2,
  "cpu": 0,
  "connections": 1,
  "total_connections": 104641,
  "routes": 2,
  "remotes": 2,
  "in_msgs": 114172,
  "out_msgs": 114167,
  "in_bytes": 3979838,
  "out_bytes": 3979335,
  "slow_consumers": 0,
  "max_pending": 268435456,
  "write_deadline": 2000000000,
  "subscriptions": 1022,
  "http_req_stats": {
    "/": 36889,
    "/connz": 0,
    "/routez": 0,
    "/subsz": 0,
    "/varz": 1
  },
  "config_load_time": "2018-11-07T11:53:41.222229141Z"
}

**Comment by kozlovic** [comment] 2018-11-09 15:46
@ivanrodolfo You are not running in clustered mode, you are running in FT mode (see FT_ACTIVE) in status. I need to add a note in the doc that FT and Clustering are not meant to be used together: it is either one mode or the other.
Can you also provide the "http://locahost:8222/varz" of the nats-streaming pod itself?
You may want to keep "file_slice_max_XXX" values default, even if you want "no limit" on your channels. It may be that your system is paging the whole files in memory and causes the streaming server to use too much (hence my request for mem usage of the streaming exe that you can get with "http://locahost:8222/varz"). Having file slices of a certain limit will cause the server to use smaller files at a given time, which may help if it is the OS paging the whole file.

**Comment by ivanrodolfo** [comment] 2018-11-09 20:12
Kozlovic,
Thanks for this information, I will change file_slice_max_XXX to a value that prevent problems with memory usage!

About FT, well I'm using this mode, I didn't remember that we changed that. When we start to use, we start to use in cluster mode, but we changed to FT because we were getting a worst performance because of sync data between nodes.

So, to maintain a better performance but without take risk to lose data, that means if I receive a ACK, then I need to be sure that this data is in my stream and is always on. So, we changed to FT mode thinking in this, I don't know if this was a better decision. 
I will try to change to cluster mode and use EBS inside my pods and see if we get a better performance!

Here varz output

/vars output:
{
  "server_id": "65Uh6tSBZ9XDnRhTB88gEU",
  "version": "1.3.0",
  "proto": 1,
  "go": "go1.11.1",
  "host": "0.0.0.0",
  "addr": "0.0.0.0",
  "max_connections": 65536,
  "ping_interval": 120000000000,
  "ping_max": 2,
  "http_host": "0.0.0.0",
  "http_port": 8222,
  "https_port": 0,
  "auth_timeout": 1,
  "max_control_line": 1024,
  "cluster": {},
  "tls_timeout": 0.5,
  "port": 4222,
  "max_payload": 1048576,
  "start": "2018-10-29T20:23:52.48414574Z",
  "now": "2018-11-09T17:18:08.955345157Z",
  "uptime": "10d20h54m16s",
  "mem": 9076736,
  "cores": 2,
  "cpu": 0,
  "connections": 0,
  "total_connections": 0,
  "routes": 0,
  "remotes": 0,
  "in_msgs": 0,
  "out_msgs": 0,
  "in_bytes": 0,
  "out_bytes": 0,
  "slow_consumers": 0,
  "max_pending": 268435456,
  "write_deadline": 2000000000,
  "subscriptions": 0,
  "http_req_stats": {
    "/": 187852,
    "/connz": 0,
    "/routez": 0,
    "/subsz": 0,
    "/varz": 1
  },
  "config_load_time": "2018-10-29T20:23:52.48414574Z"
}
======
{
  "server_id": "zSecZ5yn489TvSIQaY8r36",
  "version": "1.3.0",
  "proto": 1,
  "go": "go1.11.1",
  "host": "0.0.0.0",
  "addr": "0.0.0.0",
  "max_connections": 65536,
  "ping_interval": 120000000000,
  "ping_max": 2,
  "http_host": "0.0.0.0",
  "http_port": 8222,
  "https_port": 0,
  "auth_timeout": 1,
  "max_control_line": 1024,
  "cluster": {},
  "tls_timeout": 0.5,
  "port": 4222,
  "max_payload": 1048576,
  "start": "2018-10-29T20:46:24.100219029Z",
  "now": "2018-11-09T17:19:16.420872963Z",
  "uptime": "10d20h32m52s",
  "mem": 13172736,
  "cores": 2,
  "cpu": 0,
  "connections": 0,
  "total_connections": 0,
  "routes": 0,
  "remotes": 0,
  "in_msgs": 0,
  "out_msgs": 0,
  "in_bytes": 0,
  "out_bytes": 0,
  "slow_consumers": 0,
  "max_pending": 268435456,
  "write_deadline": 2000000000,
  "subscriptions": 0,
  "http_req_stats": {
    "/": 187595,
    "/connz": 0,
    "/routez": 0,
    "/subsz": 0,
    "/varz": 2
  },
  "config_load_time": "2018-10-29T20:46:24.100219029Z"
}

**Comment by kozlovic** [comment] 2018-11-09 20:17
I am not suggesting that you move to clustering mode, just pointed out that you were actually using FT mode, not Clustering.
The mem shows only about 8.5MB, so I don't think this is NATS Streaming using that much memory and killing your pod. Again, could be OS paging the whole file in memory, but that should not be happening to the point of exhausting all avail memory. You would need to investigate that at the OS level. There are some tooling to monitor mem usage etc..

**Comment by ivanrodolfo** [comment] 2018-11-09 22:34
Sorry, about clustering, I not think that you are suggesting me to change. I will change because I'm learning and trying some possible situations here  in my case!

About memory usage, i didn't look at /varz. I did this analysis based on my SRE monitor. At the moment that the problem occurrs, my monitor was presenting this information, all pods with low memory usage, but the master of FT was next to the limit.

I will look closely on my logs find the order that events happened!

<img width="1579" alt="screen shot 2018-11-07 at 11 35 00" src="https://user-images.githubusercontent.com/4380562/48291591-301bff00-e45e-11e8-8d8c-44b2cc539f5d.png">

**Comment by kozlovic** [comment] 2018-11-09 22:43
@ivanrodolfo Well, that's the thing. varz tells you how much memory the *process* is using, and that's from the /proc/<pid>/stat file on Linux. It has been known for containers to report incorrect data. Look at this issue that was reported a while back: https://github.com/nats-io/nats-streaming-server/issues/407#issuecomment-342627439.

**Comment by kozlovic** [comment] 2018-11-09 22:46
@ivanrodolfo and in case you miss the comment just below the one I referenced, I think this link is interesting: https://github.com/moby/moby/issues/10824

**Comment by ivanrodolfo** [comment] 2018-11-09 22:54
Well, It is very important to know about that issue. I will send more information if I change something wrong here

Thanks!

**Comment by ivanrodolfo** [comment] 2018-11-12 09:40
@kozlovic Looking at logs here! I Found something. during the period o with no connectivity my pods were connected to nats, but not to stream and stream wasnt able to connect to nats. The logs of stream:

[1] 2018/11/07 11:57:47.329057 [INF] STREAM: connection “_NSS-nats-xx-general” reconnected to NATS Server at “nats://10.x.x.1:4222"
[1] 2018/11/07 11:57:47.423323 [INF] STREAM: connection “_NSS-nats-xx-acks” reconnected to NATS Server at “nats://10.x.x.1:4222"
[1] 2018/11/07 11:57:55.429845 [INF] STREAM: connection “_NSS-nats-xx-ft” reconnected to NATS Server at “nats://10.x.x.1:4222"



At this moment we had a pod restart on nats (I don't  know why, this happened at that time). With this, what look strange for my is that I have a Cluster with three nats servers and I thing my nats-stream would be able to with this nats cluster and not  trying to connect with one specific pod. Is it a possible problem on my configs? Or is there anything specific to config with stream FT mode and nats cluster?

**Comment by kozlovic** [comment] 2018-11-12 17:06
@ivanrodolfo When you use `-nats_server_url`, you are instructing the NATS Streaming server to not embed a NATS Server and instead connect to an existing running NATS Server. If the connection to the NATS Server breaks, the Streaming server will have to reconnect to a NATS Server, either to that specific URL or any other server in the cluster that it would have discovered due to the gossip protocol between NATS Servers and its clients. What version of NATS Server are you running?

**Comment by ivanrodolfo** [comment] 2018-11-12 21:13
@kozlovic I'm running nats server v1.3.  Is there any params on nats-stream about waiting time or max timout on connections bettween nats-streaming and nats-server?

**Comment by kozlovic** [comment] 2018-11-12 21:17
Unfortunately, no. The NATS Streaming Server is a client to the NATS Server, so we would need to have the same type of settings (in this case the ping interval and max pings out) that we have for a NATS client avail to the NATS Streaming Server.

**Comment by ivanrodolfo** [comment] 2018-11-13 15:35
Well, Makes sense the ping interval and max pings out, but is it configurable?

**Comment by kozlovic** [comment] 2018-11-14 00:02
Unfortunately, this is not configurable at the moment but certainly something that we should be adding. The defaults are 1 PING every 2 minutes and a max of 2 without a response. If you want to experiment and build your version of NATS Streaming server, you would have to modify the function `createNatsClientConn()` to set the ping interval and max pings out to desired value and see if it would help. I am going to create an issue to track this enhancement request.

**Comment by ivanrodolfo** [comment] 2018-11-14 00:57
Thanks for this answer, I will consider make this change here and test. But before doing this, I think that could be somet wrong config  on my deployment. If I have a cluster of three nats-servers and and FT nats-streaming then what I would expect is that my FT nats-streaming would connect with any nats-server on my cluster and not to one of them. So a restart on one pod could impact my stream making this unavailable. 

In other hand, what would happen if I use nats stream in cluster mode in one situation like that? If a pod of nats-server restarts then my nats-streaming are have any risk of unavailability? I'm considering changing to clustering mode till I change and test this question of PingInterval and maxPingsOut

**Comment by kozlovic** [comment] 2018-11-15 16:27
If a connection breaks, the library gets notified right away and will reconnect to any NATS server in the cluster. The problem is if the connection is not marked as closed by TCP (being unreachable sometimes due to cable unplugged or more common with containers), then it takes time for TCP to report the failure. This is where application specific pings help decide if the connection is lost or not.

Clustering mode or FT would not make a difference in that regard. If the NATS Streaming server is connected to a NATS Server pod and that pod disappears without TCP reporting the failure right away, you will have the same issue.

**Comment by ssoroka** [comment] 2019-04-01 17:01
Summary: No.

**Closed** 2019-04-29 21:10 UTC
Labels: question
