### ISSUE TITLE
panic: runtime error

### ISSUE THREAD

**Issue by tharrold** [nats-io/nats-streaming-server#884] opened 2019-07-20 12:09 UTC
Hello, I am pulling my hair out on this - trying to start a new cluster (no data in store).  As soon as the raft election occurs, one node crashes with:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8049f3b]

Here is the full output, from start, with all debug enabled:

 $PWD/nats-streaming-server -sc $PWD/nss.2node.config
[11094] 2019/07/20 07:50:32.016304 [INF] STREAM: Starting nats-streaming-server[clus1] version 0.15.1
[11094] 2019/07/20 07:50:32.016612 [INF] STREAM: ServerID: 9NEjmlAD74YjT5QSUGD3Zc
[11094] 2019/07/20 07:50:32.016636 [INF] STREAM: Go version: go1.11.10
[11094] 2019/07/20 07:50:32.016655 [INF] STREAM: Git commit: [not set]
[11094] 2019/07/20 07:50:32.019050 [INF] Starting nats-server version 2.0.0
[11094] 2019/07/20 07:50:32.019117 [INF] Git commit [not set]
[11094] 2019/07/20 07:50:32.019966 [INF] Starting http monitor on 0.0.0.0:44227
[11094] 2019/07/20 07:50:32.020270 [INF] Listening for client connections on 0.0.0.0:4227
[11094] 2019/07/20 07:50:32.020328 [INF] Server id is NDP4KHELCOITHWNR437VLDV6OEABPKAH3V5BNEX5I6AMEK3JJCXZPZ6U
[11094] 2019/07/20 07:50:32.020351 [INF] Server is ready
[11094] 2019/07/20 07:50:32.021320 [INF] Listening for route connections on 0.0.0.0:6227
[11094] 2019/07/20 07:50:32.025759 [INF] 140.188.62.140:6227 - rid:1 - Route connection created
[11094] 2019/07/20 07:50:32.051774 [INF] STREAM: Recovering the state...
[11094] 2019/07/20 07:50:32.054273 [INF] STREAM: Recovered 0 channel(s)
[11094] 2019/07/20 07:50:32.054329 [INF] STREAM: Cluster Node ID : b
[11094] 2019/07/20 07:50:32.054373 [INF] STREAM: Cluster Log Path: /opt/NATS/cluster1
[11094] 2019/07/20 07:50:32.058389 [INF] STREAM:  raft: Initial configuration (index=1): [{Suffrage:Voter ID:b Address:clus1.b.clus1} {Suffrage:Voter ID:a Address:clus1.a.clus1}]
[11094] 2019/07/20 07:50:32.058457 [DBG] STREAM: Loaded existing state for Raft group clus1
[11094] 2019/07/20 07:50:32.058522 [DBG] STREAM: Discover subject:           _STAN.discover.clus1
[11094] 2019/07/20 07:50:32.058546 [DBG] STREAM: Publish subject:            _STAN.pub.clus1.>
[11094] 2019/07/20 07:50:32.058567 [DBG] STREAM: Subscribe subject:          _STAN.sub.clus1
[11094] 2019/07/20 07:50:32.058593 [DBG] STREAM: Subscription Close subject: _STAN.subclose.clus1
[11094] 2019/07/20 07:50:32.058614 [DBG] STREAM: Unsubscribe subject:        _STAN.unsub.clus1
[11094] 2019/07/20 07:50:32.058633 [DBG] STREAM: Close subject:              _STAN.close.clus1
[11094] 2019/07/20 07:50:32.058910 [INF] STREAM:  raft: Node at clus1.b.clus1 [Follower] entering Follower state (Leader: "")
[11094] 2019/07/20 07:50:32.059747 [INF] STREAM: Message store is RAFT_FILE
[11094] 2019/07/20 07:50:32.059785 [INF] STREAM: Store location: /opt/NATS/cluster1/store
[11094] 2019/07/20 07:50:32.059880 [INF] STREAM: ---------- Store Limits ----------
[11094] 2019/07/20 07:50:32.059902 [INF] STREAM: Channels:                  100 *
[11094] 2019/07/20 07:50:32.059922 [INF] STREAM: --------- Channels Limits --------
[11094] 2019/07/20 07:50:32.059940 [INF] STREAM:   Subscriptions:          1000 *
[11094] 2019/07/20 07:50:32.059958 [INF] STREAM:   Messages     :       1000000 *
[11094] 2019/07/20 07:50:32.059976 [INF] STREAM:   Bytes        :     976.56 MB *
[11094] 2019/07/20 07:50:32.059994 [INF] STREAM:   Age          :     unlimited *
[11094] 2019/07/20 07:50:32.060013 [INF] STREAM:   Inactivity   :     unlimited *
[11094] 2019/07/20 07:50:32.060031 [INF] STREAM: ----------------------------------
[11094] 2019/07/20 07:50:32.924810 [INF] 140.188.62.140:48830 - rid:7 - Route connection created
[11094] 2019/07/20 07:50:32.925166 [INF] 140.188.62.140:48830 - rid:7 - Router connection closed
[11094] 2019/07/20 07:50:33.589288 [TRC] STREAM: raft-net: clus1.b.clus1 accepted connection from: clus1.a.clus1
[11094] 2019/07/20 07:50:33.590075 [TRC] STREAM: raft: lost leadership because received a requestvote with newer term
[11094] 2019/07/20 07:50:33.590451 [WRN] STREAM:  raft: Rejecting vote request from clus1.a.clus1 since our last term is greater (260, 1)
[11094] 2019/07/20 07:50:35.568696 [WRN] STREAM:  raft: Heartbeat timeout from "" reached, starting election
[11094] 2019/07/20 07:50:35.568802 [INF] STREAM:  raft: Node at clus1.b.clus1 [Candidate] entering Candidate state in term 277
[11094] 2019/07/20 07:50:35.569495 [TRC] STREAM: raft: Votes needed: 2
[11094] 2019/07/20 07:50:35.569549 [TRC] STREAM: raft: Vote granted from b in term 277. Tally: 1
[11094] 2019/07/20 07:50:35.573495 [TRC] STREAM: raft: Vote granted from a in term 277. Tally: 2
[11094] 2019/07/20 07:50:35.573547 [INF] STREAM:  raft: Election won. Tally: 2
[11094] 2019/07/20 07:50:35.573608 [INF] STREAM:  raft: Node at clus1.b.clus1 [Leader] entering Leader state
[11094] 2019/07/20 07:50:35.573661 [INF] STREAM:  raft: Added peer a, starting replication
[11094] 2019/07/20 07:50:35.574299 [INF] STREAM: server became leader, performing leader promotion actions
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8049f3b]

goroutine 88 [running]:
runtime/internal/atomic.Load64(0x9c8d3ac, 0x9ce4ea0, 0x4)
        /home/travis/.gimme/versions/go1.11.10.linux.amd64/src/runtime/internal/atomic/asm_386.s:188 +0xb
github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.(*Raft).replicateTo(0x9cb0000, 0x9c8d380, 0x12, 0x0, 0x0)
        /home/travis/gopath/src/github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft/replication.go:205 +0xaf
github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.(*Raft).replicate(0x9cb0000, 0x9c8d380)
        /home/travis/gopath/src/github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft/replication.go:154 +0x3bb
github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.(*Raft).startStopReplication.func1()
        /home/travis/gopath/src/github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft/raft.go:488 +0x27
github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.(*raftState).goFunc.func1(0x9cb0000, 0x9ce9060)
        /home/travis/gopath/src/github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft/state.go:146 +0x44
created by github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.(*raftState).goFunc
        /home/travis/gopath/src/github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft/state.go:144 +0x54

**Comment by tharrold** [comment] 2019-07-20 12:12
Here is the config for the failing node.  (other node same, other than cluster info)

# NATS specific configuration
port: 4227
http: 0.0.0.0:44227

cluster {
  listen: 0.0.0.0:6227
  routes: [ "nats://sv26rdev01:6227" ]
}

# NATS Streaming specific configuration
streaming {
  cluster_id: clus1
  store: file
  dir: /opt/NATS/cluster1/store
  sd: true
  sv: true
  cluster {
    node_id: "b"
    peers: ["a"]
    log_path: /opt/NATS/cluster1
    raft_logging: true
  }
}

**Comment by kozlovic** [comment] 2019-07-20 16:18
@tharrold Since this is just a test, could you make sure that you stop all nodes remove all state (the raft and streaming stores) and restart?

Also, please make sure that the `dir` and `log_path` do NOT point to a central location for your nodes. That is, in cluster mode, each node stores its own set of data/meta data. If the `dir` and `log_path` would point to the same files, bad things could happen.

**Comment by kozlovic** [comment] 2019-07-20 16:22
Also, in clustered mode it is recommended to have odd-number of nodes. With 2 nodes, the cluster would not operate if one node fails.

**Comment by kozlovic** [comment] 2019-07-20 17:43
Are you running on a 32bits platform by any chance?

**Comment by kozlovic** [comment] 2019-07-20 17:43
Here is why I ask: https://github.com/hashicorp/raft/issues/343

**Comment by tharrold** [comment] 2019-07-20 18:22
Yes sir, have done that many times.  Have tried a 3 node cluster on one Linux instance, as well as a 3 node cluster on separate Linux instances. 

Definitely not using shared storage.

-tjh

**Comment by tharrold** [comment] 2019-07-20 18:24
Yes, this the Linux .386 binary running on a 64-bit red hat Linux server.

-tjh

**Comment by tharrold** [comment] 2019-07-22 16:15
Good day, some progress.  Our developer compiled a binary from the latest code, and that allowed me to get past the error I posted above.  However, now I am seeing an error when we try to use the service:

`[7975] 2019/07/22 12:11:55.865541 [DBG] STREAM: [Client:TestClient--Listener] Connected (Inbox=_INBOX.LCQWiY8jpCfBaLusOkj7AW)
[7975] 2019/07/22 12:11:55.870488 [INF] STREAM: Channel "Notifications" has been created
[7975] 2019/07/22 12:11:55.873554 [DBG] STREAM: [Client:TestClient--Listener] Started new subscription, subject=Notifications, inbox=_INBOX.LCQWiY8jpCfBaLusOkj7O4, subid=1, sending from sequence, asked_seq=1 actual_seq=1
[7975] 2019/07/22 12:11:55.881839 [DBG] STREAM: [Client:TestClient--Publisher] Connected (Inbox=_INBOX.LCQWiY8jpCfBaLusOkj7Uq)
panic: interface conversion: stores.SubStore is *stores.RaftSubStore, not *stores.FileSubStore

goroutine 1234 [running]:
github.com/nats-io/nats-streaming-server/stores.(*FileStore).autoSync(0xc000077380)
        /home/riddlmi/build_nats/nats-streaming-server-master/stores/filestore.go:1329 +0x33c
created by time.goFunc
        /usr/lib/golang/src/time/sleep.go:169 +0x44
`

**Comment by kozlovic** [comment] 2019-07-22 16:51
@tharrold Thanks! This is just in master and not in any public release. Will look into that right now.

**Comment by tharrold** [comment] 2019-07-22 17:58
We saw this after our crash, and thought it looked odd.  ("Message store is RAFT_FILE")
Is this just referencing the fact that raft messages are logging to file, not an indication that raft and our message streams are conflicting?


panic: interface conversion: stores.SubStore is *stores.RaftSubStore, not *stores.FileSubStore

goroutine 1556 [running]:
github.com/nats-io/nats-streaming-server/stores.(*FileStore).autoSync(0xc00010c300)
        /home/riddlmi/build_nats/nats-streaming-server-master/stores/filestore.go:1329 +0x33c
created by time.goFunc
        /usr/lib/golang/src/time/sleep.go:169 +0x44 
[20677] 2019/07/22 13:38:06.596739 [INF] STREAM: Cluster Node ID : b
[20677] 2019/07/22 13:38:06.596753 [INF] STREAM: Cluster Log Path: test-nss1/b
[20677] 2019/07/22 13:38:06.600464 [INF] STREAM: Message store is RAFT_FILE
[20677] 2019/07/22 13:38:06.600505 [INF] STREAM: Store location: store-nss1
[20677] 2019/07/22 13:38:06.600619 [INF] STREAM: ---------- Store Limits ----------

**Comment by kozlovic** [comment] 2019-07-22 18:05
In cluster mode, the server wraps the chosen store implementation (either FileStore or SQLStore) to a RaftStore implementation. This is what caused the panic during the FileStore's auto-sync. I have a branch up and will submit PR out of it once the tests clear. This is likely to be merged to master today after which you will be able to rebuild and verify that the problem is fixed.
Sorry for the trouble and thank you for the report!

(btw, we will probably also bring the fixes from Hashicorp's RAFT implementation soon and have a new release).

**Comment by kozlovic** [comment] 2019-07-22 18:12
Ok, PR (https://github.com/nats-io/nats-streaming-server/pull/885) is up. Should be reviewed and merge within the day. Thanks again.

**Comment by tharrold** [comment] 2019-07-22 18:13
Thank you for your response.  I get better support here than from some paid support venues.  :)

**Comment by tharrold** [comment] 2019-07-22 22:17
I see that the review was done.  Let me know when we can do a build from master, and see if it resolves the issue.  Thank you.

**Comment by kozlovic** [comment] 2019-07-22 22:19
@tharrold Done! Let me know how the testing goes.

**Comment by tharrold** [comment] 2019-07-23 13:07
So far, so good.  My configuration works, and I'm able to send test messages without crashing any of the cluster nodes.   have been able to stop/restart cluster nodes, without any crashing.

**Closed** 2019-07-25 19:36 UTC
