### ISSUE TITLE
For a given subscription, last_seq is lower than last_sent

### ISSUE THREAD

**Issue by blelump** [nats-io/nats-streaming-server#655] opened 2018-09-27 20:47 UTC
Hello,

I've observed weird subscription behavior, where `last_sent` is far above the `last_seq` value. For instance:
```
curl -X GET "http://localhost:8222/streaming/channelsz?channel=sub_name&subs=1"                                  
{                                                                                                                                              
  "name": "sub_name",                                                                                                                       
  "msgs": 9,                                                
  "bytes": 14607,                                                                                                                                                               
  "first_seq": 1,                                                        
  "last_seq": 9,                                                                                                                                                                
  "subscriptions": [                                           
    {                                                                                                                                                                           
      "client_id": "basket",                                 
      "inbox": "ef8a68605472c1df7b88636838",                                                                                                    
      "ack_inbox": "_INBOX.mp6XYgPKFRe9PK9XiQW0gv",
      "queue_name": "basket:basket",               
      "is_durable": true,           
      "is_offline": false, 
      "max_inflight": 1024,
      "ack_wait": 30,                                                                                                                                                           
      "last_sent": 57,                                                  
      "pending_count": 0,                                                                                                                                                      
      "is_stalled": false                                                                                                                      
    }                                                                                                                                                                           
  ]  
```

The result of that is all messages are being ignored until `last_seq > last_sent`. Is it expected behavior? If so, how to avoid it? 

Thanks!

**Comment by kozlovic** [comment] 2018-09-27 22:08
That's not expected, no. Which version of the server? Is it running in clustered mode or standalone mode? There has been some issues with subscriptions in cluster mode that have been fixed in 0.10.2.
Any chance that you would have deleted the message store files (`<datastore>/<channel name>/msgs.*.*`) but not the subscriptions (`<datastore>/<channel name>/subs.dat`)?

**Comment by blelump** [comment] 2018-09-27 22:42
Hi @kozlovic , 

thanks for reponse! I am on the newest version 0.11 (dockerized, single node) using PSQL as a datastore. My teammates are observing similar issues. We're using node & ruby clients with queue groups and durable names features.

**Comment by kozlovic** [comment] 2018-09-27 23:04
If you could try to reproduce from scratch and run server with `-SDV` (to get debug and trace level) and provide the log files for review that would be great! (I am not able to reproduce with simple test at the moment).

**Comment by kozlovic** [comment] 2018-09-27 23:06
Any possibility that someone/something external would have deleted messages from the messages table? There is nothing that prevents you from doing that.

**Comment by blelump** [comment] 2018-09-27 23:15
I know :smile: , but I really doubt it. I've started fresh NATS DB and we'll see. 

Any chance PostgreSQL storage may be related? I may switch to file storage

**Comment by kozlovic** [comment] 2018-09-27 23:17
If you could reproduce that would be great! This issue has never been reported before. It could be specific to SQL, but even then, it was never reported. So would be nice to get to the bottom of this.

**Comment by kozlovic** [comment] 2018-09-27 23:31
Oh, thanks for that! I stopped my server and restarted with similar settings except that I used a very small max_age (10 minutes) and the messages were gone (as expected) and so subscriptions show the same pattern (last_sent > 0). What's not right is that next message should start at previous last_seq+1, in other words, when all messages are expired, we need to keep track of what the last_seq was. I thought I fixed that at one point but visibly not.

Could it be what happened in your case?

**Comment by kozlovic** [comment] 2018-09-27 23:39
There is clearly an issue with message expiration and SQL store, sorry about that.. Looking into it.

**Comment by blelump** [comment] 2018-09-27 23:46
@kozlovic , uhm, let me summarize your comment: 
There were messages that has expired, because no one was interested in them for 48h?  Is it likely that given message happen to fail every time during execution on subscriber and hence -- as I understand -- was not ack'ed and after 48h has been removed from storage? Then the counter `last_sent` has not been decreased, even though message has been deleted?

If that's the case then yes, it is possible that such failing  messages without ack  may exist in the system.

**Comment by kozlovic** [comment] 2018-09-27 23:50
Ack'ing or interest does not come into play with NATS Streaming and message age. The max_age simply means that messages with a timestamp + max_age lower than current time are removed from the messages log.

So say you send 1 message every second and have a max age of 10 seconds, every second, the oldest message will be removed, regardless of subscriptions interest, etc..

At runtime the server is doing the right thing. The issue is in recovery where it is possible that server loses track of what was the last sequence. So it would be possible that it restart the sequencing from 1 or other value that is less than what was the previous last sequence number (explaining the different of last_sent > (new) last_seq).

**Comment by blelump** [comment] 2018-09-27 23:55
I see :+1:  . Do you think, you're able to fix? I may quit docker image and switch to _bare metal_ NATS and start with file datastore.

**Comment by kozlovic** [comment] 2018-09-27 23:57
I have to fix it ;-) but if you are experimenting, then you could use file store for now. Thanks for your patience and report!

**Comment by blelump** [comment] 2018-09-27 23:59
@kozlovic , we're using it in beta, not just development , so I guess I'll switch to bare metal in order to get it on the right track .

Thanks for your assistance!

**Comment by kozlovic** [comment] 2018-09-28 00:55
@blelump Not sure if you have the ability to compile and test the PR #656 and see if that fixes the issue you have been seeing. If you can, great, otherwise, I am confident that there was an issue and added a test that demonstrated the issue (without the fix) and correct as expected with the fix.

**Comment by blelump** [comment] 2018-10-01 13:17
Hi @kozlovic , 

I was not able to compile it yet, but we started to observe similar issues with DIR datastore. Is this even possible?

```
{
  "name": "queuing.v1.topic_name",
  "msgs": 62,
  "bytes": 9373966,
  "first_seq": 1,
  "last_seq": 62,
  "subscriptions": [
    {
      "client_id": "catalog2",
      "inbox": "_INBOX.9LK91P9D6Q1K801L2KT5S4",
      "ack_inbox": "_INBOX.d9jWly5KeeU6jJUWoNJnKL",
      "queue_name": "cls:cls",
      "is_durable": true,
      "is_offline": true,
      "max_inflight": 16384,
      "ack_wait": 30,
      "last_sent": 56,
      "pending_count": 0,
      "is_stalled": false
    }
  ]
}
```

Perhaps it is due to `"is_offline": true`?

**Comment by kozlovic** [comment] 2018-10-01 15:13
I don't see that: here, `last_seq` is 62 but subscription's `last_sent` is 56, which is below.

**Comment by blelump** [comment] 2018-10-01 16:57
You're absolutely right, sorry for interrupting!

**Comment by kozlovic** [comment] 2018-10-01 16:58
No problem! I can merge the PR about the SQL fix if that makes it easier for you to fix? (instead of waiting for you to test the PR?)

**Comment by blelump** [comment] 2018-10-02 13:57
@kozlovic , sorry for late reply.

I've digged into it today and failed while trying to compile(I am not golang guy). Here is what I've tried:
```
go build
nats-streaming-server.go:28:2: cannot find package "github.com/lib/pq" in any of:
	/usr/lib/go-1.10/src/github.com/lib/pq (from $GOROOT)
       ...
```

so I've found `vendor` dir with these missing deps, but I don't know how to use it , sorry for that. I've also tried `scripts/cross_compile.sh` , but it failed `env: ‘gox’: No such file or directory`. I'd be glad if you could provide me a few steps how to deal with it. Thanks!

**Comment by kozlovic** [comment] 2018-10-02 15:18
Sorry about that. From the nats-streaming-server top level directory, please do a `go get -u`. This will download all needed dependencies. Then you can compile.

**Comment by kozlovic** [comment] 2018-10-03 15:43
@blelump Actually, yes, dependencies are vendor'ed so you should not need anything to build the executable (you would need for running the tests though).

First, you need to make sure that the repo has the following directory structure: `github.com/nats-io/nats-streaming-server/` (and sources are in that last directory).
If you have the above directory structure in your `<go home>/src` directory, then you are good to go. The `go build` should now work.

If you download the nats server repo outside of the `<go home>/src` directory, like say in `/home/blelump/testnss` first make sure that you have the proper directory structure such as `/home/blelump/testnss/src/github.com/nats-io/nats-streaming-server/`, in other words, unpack the nats-streaming-server directory in `/home/blelump/testnss/src/github.com/nats-io/nats-streaming-server/`. Then, set your `GOPATH` to `/home/bluemp/testnss` (do not include `src` in there) and then from nats-streaming-server directory, you should now be able to compile.

**Comment by kozlovic** [comment] 2018-10-05 20:33
But you would need to first build the image with https://github.com/nats-io/nats-streaming-server/blob/master/Dockerfile, then extract the executable from there and only then use the Dockerfile that you pointed. This what https://github.com/nats-io/nats-streaming-docker/blob/master/update.sh is doing. 
So from `nats-streaming-docker` directory, you could do:
```
./update.sh fix_sqlstore_recovery_expire_msgs
```
This will build the images for the given branch. Then:
```
cd amd64
docker build -t my_nats_streaming .
```

**Closed** 2018-10-16 01:10 UTC
Labels: bug

**Comment by sega-yarkin** [comment] 2019-02-19 20:55
Hi @kozlovic, I found the same issue in one of my NATS Streaming installation, but with file storage and older server version (`0.9.2`).
```json
{
  "name": "...",
  "msgs": 0,
  "bytes": 0,
  "first_seq": 1063,
  "last_seq": 1062,
  "subscriptions": [
    {
      "client_id": "...",
      "inbox": "...",
      "ack_inbox": "...",
      "queue_name": "group",
      "is_durable": false,
      "is_offline": false,
      "max_inflight": 256,
      "ack_wait": 30,
      "last_sent": 0,
      "pending_count": 0,
      "is_stalled": false
    },
    {
      "client_id": "...",
      "inbox": "...",
      "ack_inbox": "...",
      "queue_name": "group",
      "is_durable": false,
      "is_offline": false,
      "max_inflight": 256,
      "ack_wait": 30,
      "last_sent": 0,
      "pending_count": 0,
      "is_stalled": false
    }
  ]
},
```
The channel is used very rarely, so I think there might were few restarts since the last message. Also there is a policy with `max_age = 7 days` and `slice_max_age = 6 hours` (`max_msgs=0`, `max_bytes=0`, `slice_max_msgs=0`, `slice_max_bytes=0`), you can see there're no messages in the channel right now (`"msgs": 0`). A problem is I don't know a reason and a way to reproduce it (also can't upgrade version right now), so I just leave the comment.

**Comment by kozlovic** [comment] 2019-02-19 21:23
The fact that `first_seq` is higher than `last_seq` is expected since all messages have expired. The `last_sent` being 0 for both is a bit strange. I can't reproduce this (even with 0.9.2). What I see is that when I start the first queue sub (non durable as in your example), then the last_sent is equal to `last_seq`. The second queue member last_sent is set to 0. So could it be that you truncated the output and have more members on that same queue group?
What options do you use for the queue members (like start sequence, etc..) and were those queue subscriptions started before messages expired?

**Comment by sega-yarkin** [comment] 2019-02-19 22:31
No, there are only two subscribers for the channel, and both were created after the latest server restart (according to services uptime). I'm not 100% sure, but it looks like there were no messages sent into the channel for last 30 days, NATS Streaming server uptime is 20 days, expiration is 7 days, and subscribers uptime is about 6.5 days. Subscriptions are not durable and with start point at the end of channel. But most likely the queue group hasn't been removed for a long time because of service (subscriber) restart policy (old instances are terminated only after few of new ones are created). I can terminate all subscribers for few seconds and then start them again (to ensure queue group is removed) for test purpose.

Do you have plans to add timestamps for objects returned by monitoring endpoint (if it isn't done yet)?

**Comment by kozlovic** [comment] 2019-02-20 16:53
I am not able to reproduce both queue members at a start sequence of 0. At least one of them is showing the right sequence (last_sent == last_seq) and regardless, both receive correctly new messages.
About timestamp, are you asking timestamp when those objects were created (in case of subscriptions for instance)? We do report "now" in the returned object as the time of the capture. For objects, except messages (which we don't report) others don't have a timestamp in the protobuf used to create/store them so that would not be possible at the moment.

**Comment by sega-yarkin** [comment] 2019-02-20 19:58
Yeah, I don't know how to reproduce it either. Have you tried to connect third one and disconnect the first (with non-zero last_sent) without sending any messages? What is the purpose of setting start sequence only for the first client, why not for every one?

> About timestamp, are you asking timestamp when those objects were created

Correct, in this case it would be a little easier to reconstruct part of history when you don't have detailed logs and have got a strange state.
